#!/usr/bin/env node
/*
 * gen_coach_book.js — the opening book's TABLES, in Swift, from the JS twin's own tables.
 *
 *     node tools/metrics/gen_coach_book.js
 *
 * Same argument as `gen_coach_metrics.js`: 63 repertoire rows plus two junk pools is exactly the
 * kind of data where a hand-copied Swift twin is one transposed SAN away from a bot that silently
 * falls through to the engine on every line it touches — and silently is the operative word, since
 * spec §2.3 requires an unplayable book move to fall through rather than fail.
 *
 * Only the DATA is generated. The lookup lives in `CoachBook.swift` and is transliterated, because
 * it is logic rather than a table and `replay_coach.js` checks it against the JS directly.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const BOOK = require(path.join(ROOT, 'web-demo', 'js', 'coach-book.js'));
const OUT = path.join(ROOT, 'Sources', 'BiyaherongCoachCore', 'CoachBookData.swift');

function swiftString(str) {
  let out = '';
  for (const ch of str) {
    const c = ch.codePointAt(0);
    if (ch === '"') out += '\\"';
    else if (ch === '\\') out += '\\\\';
    else if (c < 0x20 || c > 0x7e) out += '\\u{' + c.toString(16).toUpperCase() + '}';
    else out += ch;
  }
  return '"' + out + '"';
}

const list = (xs) => '[' + xs.map(swiftString).join(', ') + ']';

function rowLiteral(row) {
  const [history, move, atPly] = row;
  if (history === null) {
    if (typeof atPly !== 'number') {
      console.error('FATAL: a ply-gated row has no ply count: ' + JSON.stringify(row));
      process.exit(1);
    }
    return 'Row(atPly: ' + atPly + ', move: ' + swiftString(move) + ')';
  }
  if (!Array.isArray(history) || typeof move !== 'string') {
    console.error('FATAL: unrecognised book row shape: ' + JSON.stringify(row));
    process.exit(1);
  }
  return 'Row(history: ' + list(history) + ', move: ' + swiftString(move) + ')';
}

const levels = Object.keys(BOOK.RULES).map(Number).sort((a, b) => a - b);
let rowCount = 0;
const tables = levels.map((lv) => {
  const sides = BOOK.RULES[lv];
  const sideText = ['w', 'b'].map((side) => {
    const rows = sides[side] || [];
    rowCount += rows.length;
    const body = rows.map((r) => '            ' + rowLiteral(r) + ',').join('\n');
    return '        .' + (side === 'w' ? 'white' : 'black') + ': [\n' + body + '\n        ],';
  }).join('\n');
  return '    ' + lv + ': [\n' + sideText + '\n    ],';
}).join('\n');

if (rowCount < 60) {
  console.error('FATAL: only ' + rowCount + ' book rows — the table looks truncated');
  process.exit(1);
}

const text = `// GENERATED by tools/metrics/gen_coach_book.js — DO NOT HAND-EDIT.
//
// The opening book's tables (spec §2.3), emitted from \`web-demo/js/coach-book.js\` so the two
// languages hold ONE book rather than two readings of one. The lookup that walks these rows is in
// \`CoachBook.swift\` and is transliterated, not generated.
//
// ${rowCount} repertoire rows across levels ${levels.join(', ')}, plus level 1's two junk pools.

import Foundation

extension CoachBook {

    /// Seven moves per side. \`sanHistory.count < bookPlies\` is the spec's own gate.
    public static let bookPlies = ${BOOK.BOOK_PLIES}

    /// Level 1 — Jaden. Not a line, a POOL: uniform over openings that are all bad on purpose.
    /// This IS the level's character, and after move 1 the depth-2 search takes over.
    public static let l1White: [String] = ${list(BOOK.L1_WHITE)}
    public static let l1Black: [String] = ${list(BOOK.L1_BLACK)}

    /// Levels 2–5. Order does not matter: the lookup is an exact match on the history, so at most
    /// one row can apply.
    public static let rules: [Int: [CoachGame.Side: [Row]]] = [
${tables}
    ]
}
`;
fs.writeFileSync(OUT, text);
console.log('wrote Sources/BiyaherongCoachCore/CoachBookData.swift ('
  + rowCount + ' rows, ' + (fs.statSync(OUT).size / 1024).toFixed(1) + ' KB)');
