/* coach-metrics.js — Play vs Coach's pure presentation layer.
 *
 * GENERATED by tools/metrics/gen_coach_metrics.js — DO NOT HAND-EDIT.
 *
 * Twin of `DemoApp/Sources/BiyaherongUI/CoachMetrics.swift`. Both are emitted from
 * `tools/metrics/coach_styles.json`, which `extract_coach_styles.js` re-derives from the React
 * Native source on every run.
 *
 * Consequently the screens contain NO numeric literal and NO arithmetic in a render body. Break that
 * and the coverage drains out silently: an inlined number is a number no check can see.
 */
'use strict';

var BiyaCoachMetrics = (function () {

  var SELECT = {
      container: { flex: 1, backgroundColor: '#070E20' },
      bgGlowA: { position: 'absolute', width: 585, height: 585, borderRadius: 292.5, backgroundColor: 'rgba(0, 80, 200, 0.16)', bottom: -280.8, left: -97.5 },
      bgGlowB: { position: 'absolute', width: 380.25, height: 380.25, borderRadius: 190.125, backgroundColor: 'rgba(0, 140, 255, 0.1)', bottom: -128.7, left: 4.875 },
      scroll: { paddingBottom: 36 },
      backBtn: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center', marginTop: 8, marginLeft: 10 },
      backIcon: { fontSize: 26, color: '#FFFFFF' },
      titleBlock: { alignItems: 'center', paddingHorizontal: 24, paddingBottom: 22, paddingTop: 4 },
      titleTopRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
      knightDecor: { fontSize: 16, color: '#FFFFFF', opacity: 0.85 },
      titleSmall: { fontSize: 12, fontWeight: '700', color: '#FFFFFF', letterSpacing: 2 },
      titleLarge: { fontSize: 30, fontWeight: '900', color: '#FDB022', textAlign: 'center', lineHeight: 35, letterSpacing: 0.8, textTransform: 'uppercase' },
      chessPieceAccent: { fontSize: 22, color: '#FDB022', marginTop: 2, marginBottom: 2 },
      titleSub: { fontSize: 13, color: 'rgba(255,255,255,0.85)', marginTop: 6, textAlign: 'center', lineHeight: 18 },
      row1: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', paddingHorizontal: 4, marginBottom: 6 },
      row2: { flexDirection: 'row', justifyContent: 'center', alignItems: 'flex-end', paddingHorizontal: 31.2, gap: 16, marginBottom: 22 },
      coachCard: { flex: 1, alignItems: 'center', paddingHorizontal: 4, paddingBottom: 4 },
      coachCardFeatured: { flex: 1.15 },
      glowHalo: { justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 160, 255, 0.07)', marginBottom: 8 },
      glowHaloFeatured: { backgroundColor: 'rgba(0, 200, 255, 0.1)' },
      glowHaloLocked: { backgroundColor: 'rgba(80, 80, 80, 0.07)' },
      cyanRing: { justifyContent: 'center', alignItems: 'center', borderWidth: 2.5, borderColor: 'rgba(0, 220, 255, 0.95)', backgroundColor: 'rgba(4, 20, 60, 0.5)', shadowColor: '#00CFFF', shadowOffset: {"width":0,"height":0}, shadowOpacity: 0.9, shadowRadius: 8, elevation: 6 },
      cyanRingFeatured: { borderWidth: 3, borderColor: '#00E5FF', shadowRadius: 14, shadowOpacity: 1 },
      cyanRingLocked: { borderColor: 'rgba(120, 120, 120, 0.5)', shadowOpacity: 0.2 },
      lockOverlay: { position: 'absolute', justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.35)' },
      lockIcon: { fontSize: 22 },
      premiumTag: { backgroundColor: 'rgba(253,176,34,0.15)', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, borderColor: '#FDB022', marginTop: 2 },
      premiumTagText: { fontSize: 9, color: '#FDB022', fontWeight: '700', letterSpacing: 0.5 },
      coachName: { fontSize: 13, fontWeight: '700', color: '#FFFFFF', textAlign: 'center', marginBottom: 1 },
      coachNameFeatured: { fontSize: 16, fontWeight: '900' },
      coachNameLocked: { color: 'rgba(255,255,255,0.45)' },
      coachRole: { fontSize: 10, color: '#FDB022', textAlign: 'center', fontWeight: '600' },
      coachRoleFeatured: { fontSize: 12 },
      coachRating: { fontSize: 10, color: '#8BA3C7', fontWeight: '700', textAlign: 'center', marginTop: 1 },
      coachRatingFeatured: { fontSize: 12, color: '#FDB022' },
      coachDesc: { fontSize: 9, color: 'rgba(255,255,255,0.55)', textAlign: 'center', marginTop: 1 },
      settingsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginHorizontal: 24, marginBottom: 18, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 14, paddingHorizontal: 18, paddingVertical: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
      settingsLabel: { fontSize: 14, fontWeight: '700', color: '#FFFFFF' },
      footer: { alignItems: 'center', paddingHorizontal: 20, paddingTop: 4 },
      footerBold: { fontSize: 21, fontWeight: '900', color: '#FDB022', textAlign: 'center', marginBottom: 5 },
      footerLight: { fontSize: 12, color: 'rgba(255,255,255,0.65)', fontStyle: 'italic', textAlign: 'center', letterSpacing: 1.5 },
      cardSize: { avatarRegular: 80, ringRegular: 86, haloRegular: 96, avatarFeatured: 108, ringFeatured: 114, haloFeatured: 124 },
    };

  var PLAY = {
      container: { flex: 1, backgroundColor: '#07111F' },
      backBtn: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
      backIcon: { fontSize: 26, color: '#FFFFFF' },
      selTopGlow: { position: 'absolute', top: 0, left: 0, right: 0, height: 429.00000000000006, borderBottomLeftRadius: 214.50000000000003, borderBottomRightRadius: 214.50000000000003 },
      selScroll: { paddingBottom: 36 },
      selIntroBlock: { alignItems: 'center', paddingHorizontal: 24, paddingTop: 4, paddingBottom: 18 },
      selHalo: { width: 136, height: 136, borderRadius: 68, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.15)', shadowOffset: {"width":0,"height":0}, shadowOpacity: 0.45, shadowRadius: 22, elevation: 10, marginBottom: 10 },
      selRing: { width: 120, height: 120, borderRadius: 60, borderWidth: 3, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(4, 16, 48, 0.65)', shadowOffset: {"width":0,"height":0}, shadowOpacity: 0.9, shadowRadius: 14, elevation: 8 },
      selAvatarImg: { width: 112, height: 112, borderRadius: 56 },
      starsRow: { flexDirection: 'row', gap: 5, marginBottom: 8 },
      star: { fontSize: 22 },
      selName: { fontSize: 27, fontWeight: '900', color: '#FFFFFF', textAlign: 'center', marginBottom: 3 },
      selRole: { fontSize: 14, fontWeight: '700', textAlign: 'center', marginBottom: 4 },
      selTagline: { fontSize: 11, color: 'rgba(255,255,255,0.4)', textAlign: 'center', letterSpacing: 0.3, marginBottom: 10 },
      selRatingBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 12, paddingHorizontal: 14, paddingVertical: 5, marginBottom: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
      selRatingLabel: { fontSize: 11, fontWeight: '700', color: 'rgba(255,255,255,0.45)', letterSpacing: 1 },
      selRatingValue: { fontSize: 16, fontWeight: '900', letterSpacing: 0.5 },
      selBubbleWrap: { width: '100%', alignItems: 'center' },
      selTriangle: { width: 0, height: 0, borderLeftWidth: 11, borderRightWidth: 11, borderBottomWidth: 14, borderLeftColor: 'transparent', borderRightColor: 'transparent', marginBottom: -1 },
      selBubble: { width: '100%', backgroundColor: 'rgba(8, 20, 50, 0.97)', borderRadius: 18, borderWidth: 1, paddingHorizontal: 20, paddingVertical: 16 },
      selBubbleText: { fontSize: 13, color: '#D4E8F8', lineHeight: 21, fontStyle: 'italic', textAlign: 'center' },
      colorSection: { paddingHorizontal: 20, paddingBottom: 16, gap: 14 },
      colorLabel: { fontSize: 14, fontWeight: '700', color: '#FFFFFF', textAlign: 'center', letterSpacing: 1, opacity: 0.9 },
      colorRow: { flexDirection: 'row', gap: 12 },
      colorCard: { flex: 1, borderRadius: 20, paddingVertical: 24, alignItems: 'center', gap: 6, borderWidth: 2 },
      colorCardWhite: { backgroundColor: '#EFF3F8', borderColor: '#CBD5E1' },
      colorCardBlack: { backgroundColor: '#0F1520', borderColor: '#2C3A50' },
      kingW: { fontSize: 44, color: '#1E293B' },
      colorNameW: { fontSize: 17, fontWeight: '800', color: '#1E293B' },
      colorHintW: { fontSize: 11, color: '#64748B' },
      kingB: { fontSize: 44, color: '#FFFFFF' },
      colorNameB: { fontSize: 17, fontWeight: '800', color: '#FFFFFF' },
      colorHintB: { fontSize: 11, color: '#94A3B8' },
      savedGameBanner: { marginHorizontal: 20, marginTop: 4, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: 'rgba(253, 176, 34, 0.1)', borderRadius: 12, borderWidth: 1, borderColor: 'rgba(253, 176, 34, 0.35)', paddingHorizontal: 14, paddingVertical: 10 },
      savedGameIcon: { fontSize: 16 },
      savedGameText: { flex: 1, fontSize: 12, color: 'rgba(253, 176, 34, 0.9)', fontWeight: '600' },
      playHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingTop: 6, paddingBottom: 6 },
      playHeaderCenter: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
      headerAvatarRing: { width: 42, height: 42, borderRadius: 21, borderWidth: 2, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
      headerAvatarImg: { width: 38, height: 38, borderRadius: 19 },
      headerName: { fontSize: 15, fontWeight: '800', color: '#FFFFFF' },
      headerRole: { fontSize: 11, fontWeight: '600', marginTop: 1 },
      colorBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, minWidth: 74, alignItems: 'center' },
      colorBadgeW: { backgroundColor: 'rgba(255,255,255,0.1)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)' },
      colorBadgeB: { backgroundColor: 'rgba(0,0,0,0.3)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)' },
      colorBadgeText: { fontSize: 11, fontWeight: '600', color: '#FFFFFF' },
      talkStrip: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.04)', marginHorizontal: 12, marginBottom: 4, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, gap: 10, minHeight: 50 },
      talkAvatarRing: { width: 40, height: 40, borderRadius: 20, borderWidth: 2, justifyContent: 'center', alignItems: 'center', flexShrink: 0, overflow: 'hidden' },
      talkAvatarImg: { width: 36, height: 36, borderRadius: 18 },
      talkRight: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
      talkSpinner: { flexShrink: 0 },
      talkText: { flex: 1, fontSize: 12, color: 'rgba(255,255,255,0.78)', fontStyle: 'italic', lineHeight: 18 },
      premoveChip: { backgroundColor: 'rgba(255, 193, 7, 0.2)', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, borderWidth: 1, borderColor: 'rgba(255, 193, 7, 0.5)' },
      premoveChipText: { fontSize: 10, fontWeight: '700', color: '#FDB022' },
      gameOverChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10, flexShrink: 0 },
      gameOverChipText: { fontSize: 11, fontWeight: '800', color: '#FFFFFF' },
      modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center' },
      modalCard: { backgroundColor: '#0D1B30', borderRadius: 22, paddingVertical: 24, paddingHorizontal: 28, alignItems: 'center', width: 334, borderWidth: 1, gap: 6 },
      modalAvatarRing: { width: 68, height: 68, borderRadius: 34, borderWidth: 3, justifyContent: 'center', alignItems: 'center', overflow: 'hidden', marginBottom: 4 },
      modalAvatarImg: { width: 60, height: 60, borderRadius: 30 },
      modalResultEmoji: { fontSize: 32 },
      modalResultLabel: { fontSize: 22, fontWeight: '900', textAlign: 'center' },
      modalResultText: { fontSize: 13, fontWeight: '600', textAlign: 'center', lineHeight: 20, paddingHorizontal: 4, opacity: 0.85 },
      modalActions: { flexDirection: 'row', gap: 10, marginTop: 10 },
      modalBtn: { paddingHorizontal: 24, paddingVertical: 11, borderRadius: 14, minWidth: 100, alignItems: 'center' },
      modalBtnText: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },
      modalBtnOutline: { backgroundColor: 'transparent', borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.2)' },
      modalBtnTextOutline: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },
      modalReviewBtn: { marginTop: 6, paddingHorizontal: 28, paddingVertical: 11, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
      modalReviewBtnText: { fontSize: 14, fontWeight: '700', color: '#D4E8F8' },
      reviewModalCard: { backgroundColor: '#0D1B30', borderRadius: 22, paddingVertical: 20, paddingHorizontal: 20, width: 350, borderWidth: 1, maxHeight: '85%' },
      reviewModalTitle: { fontSize: 16, fontWeight: '900', color: '#FFFFFF', textAlign: 'center', letterSpacing: 2, marginBottom: 14 },
      reviewLoadingWrap: { alignItems: 'center', paddingVertical: 40, gap: 12 },
      reviewLoadingText: { fontSize: 14, fontWeight: '700', color: '#FFFFFF' },
      reviewLoadingHint: { fontSize: 12, color: 'rgba(255,255,255,0.4)' },
      reviewPlayersRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
      reviewPlayerCol: { flex: 1, alignItems: 'center', gap: 2 },
      reviewPlayerLabel: { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.7)', marginBottom: 2 },
      reviewAccuracyValue: { fontSize: 28, fontWeight: '900' },
      reviewAccuracyLabel: { fontSize: 10, fontWeight: '600', color: 'rgba(255,255,255,0.35)', letterSpacing: 1, textTransform: 'uppercase' },
      reviewDivider: { width: 1, height: 50, backgroundColor: 'rgba(255,255,255,0.12)', marginHorizontal: 12 },
      reviewGraphWrap: { alignItems: 'center', marginBottom: 14 },
      reviewClassificationsBlock: { gap: 5, marginBottom: 16 },
      reviewClassRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
      reviewClassCount: { fontSize: 15, fontWeight: '800', width: 30, textAlign: 'center' },
      reviewClassDot: { width: 8, height: 8, borderRadius: 4 },
      reviewClassLabel: { fontSize: 13, fontWeight: '600', color: 'rgba(255,255,255,0.7)', width: 90, textAlign: 'center' },
      reviewModalActions: { flexDirection: 'row', gap: 10 },
      reviewStartBtn: { flex: 1, paddingVertical: 13, borderRadius: 14, alignItems: 'center' },
      reviewStartBtnText: { fontSize: 15, fontWeight: '900', color: '#FFFFFF' },
      reviewNewGameBtn: { flex: 1, paddingVertical: 13, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', alignItems: 'center' },
      reviewNewGameBtnText: { fontSize: 15, fontWeight: '800', color: '#FFFFFF' },
      moveStrip: { maxHeight: 36, marginHorizontal: 12, marginBottom: 4 },
      moveStripContent: { alignItems: 'center', paddingHorizontal: 4, gap: 2 },
      movePairGroup: { flexDirection: 'row', alignItems: 'center', gap: 1 },
      movePairNum: { fontSize: 11, color: 'rgba(255,255,255,0.3)', paddingHorizontal: 3, fontFamily: 'Menlo' },
      moveToken: { paddingHorizontal: 6, paddingVertical: 4, borderRadius: 6, backgroundColor: 'transparent' },
      moveTokenActive: { backgroundColor: '#FDB022' },
      moveTokenText: { fontSize: 12, color: 'rgba(255,255,255,0.65)', fontFamily: 'Menlo' },
      moveTokenTextActive: { color: '#07111F', fontWeight: '700' },
      navBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 6, gap: 4 },
      navBtn: { width: 44, height: 34, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.08)', justifyContent: 'center', alignItems: 'center' },
      navBtnDisabled: { opacity: 0.3 },
      navBtnText: { fontSize: 16, color: '#FFFFFF' },
      navLiveBtn: { flex: 1, height: 34, borderRadius: 8, backgroundColor: '#1A3560', justifyContent: 'center', alignItems: 'center', marginHorizontal: 4 },
      navLiveBtnText: { fontSize: 12, fontWeight: '700', color: '#FDB022' },
      navLiveIndicator: { flex: 1, height: 34, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.04)', justifyContent: 'center', alignItems: 'center', marginHorizontal: 4, flexDirection: 'row', gap: 5 },
      navLiveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#4CAF50' },
      navLiveLabel: { fontSize: 10, fontWeight: '700', color: '#4CAF50', letterSpacing: 1 },
      openingPanel: { position: 'absolute', left: 12, right: 12, bottom: 60, zIndex: 100, maxHeight: 280, backgroundColor: 'rgba(10, 25, 55, 0.97)', borderRadius: 14, borderWidth: 1, borderColor: 'rgba(253, 176, 34, 0.3)', padding: 12 },
      openingPanelHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
      openingPanelTitle: { fontSize: 13, fontWeight: '800', color: '#FDB022' },
      openingPanelActions: { flexDirection: 'row', gap: 8, alignItems: 'center' },
      openingRefreshBtn: { width: 28, height: 28, borderRadius: 7, backgroundColor: 'rgba(255,255,255,0.08)', justifyContent: 'center', alignItems: 'center' },
      openingRefreshText: { fontSize: 16, color: '#FDB022' },
      openingCloseBtn: { width: 28, height: 28, borderRadius: 7, backgroundColor: 'rgba(255,255,255,0.08)', justifyContent: 'center', alignItems: 'center' },
      openingCloseText: { fontSize: 14, color: 'rgba(255,255,255,0.6)' },
      openingLoadingRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8 },
      openingLoadingText: { fontSize: 12, color: 'rgba(255,255,255,0.5)' },
      openingNameBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8, backgroundColor: 'rgba(253, 176, 34, 0.12)', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
      openingNameEco: { fontSize: 11, fontWeight: '800', color: '#FDB022' },
      openingNameText: { fontSize: 11, fontWeight: '600', color: '#D4E8F8', flex: 1 },
      openingStatsBlock: { marginBottom: 8 },
      openingStatsLabel: { fontSize: 10, color: 'rgba(255,255,255,0.4)', marginBottom: 4 },
      openingBar: { height: 8, borderRadius: 4, flexDirection: 'row', overflow: 'hidden', marginBottom: 4 },
      openingBarSeg: { height: 8 },
      openingBarLegend: { flexDirection: 'row', justifyContent: 'space-between' },
      openingBarLegendText: { fontSize: 10, fontWeight: '600' },
      openingMovesBlock: { marginTop: 2 },
      openingMovesTitle: { fontSize: 11, fontWeight: '700', color: 'rgba(255,255,255,0.5)', marginBottom: 6, letterSpacing: 0.5 },
      openingMoveRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)', gap: 8 },
      openingMoveSan: { fontSize: 13, fontWeight: '700', color: '#FFFFFF', width: 44, fontFamily: 'Menlo' },
      openingMoveStats: { flex: 1, fontSize: 11, color: 'rgba(255,255,255,0.5)' },
      openingMoveRating: { fontSize: 10, fontWeight: '600' },
      openingNoData: { fontSize: 12, color: 'rgba(255,255,255,0.4)', textAlign: 'center', paddingVertical: 8 },
      bottomBar: { flexDirection: 'row', paddingHorizontal: 12, paddingBottom: 8, paddingTop: 4, gap: 8 },
      actionBtn: { paddingVertical: 10, borderRadius: 12, alignItems: 'center', justifyContent: 'center', minWidth: 44 },
      actionBtnDisabled: { opacity: 0.4 },
      resignBtn: { flex: 1, backgroundColor: '#7F1D1D', borderWidth: 1, borderColor: 'rgba(255, 80, 80, 0.3)' },
      resignText: { fontSize: 13, fontWeight: '700', color: '#FFCDD2' },
      takeBackBtn: { flex: 1, backgroundColor: '#78350F', borderWidth: 1, borderColor: 'rgba(253, 176, 34, 0.3)' },
      takeBackText: { fontSize: 12, fontWeight: '700', color: '#FDE68A' },
      explorerBtn: { flex: 1, backgroundColor: '#0F2545', borderWidth: 1, borderColor: 'rgba(253, 176, 34, 0.3)' },
      explorerBtnText: { fontSize: 12, fontWeight: '700', color: '#FDB022' },
      newColorBtn: { flex: 1, backgroundColor: '#1B3050', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)' },
      newColorText: { fontSize: 13, fontWeight: '700', color: '#FFFFFF' },
      promotionOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', alignItems: 'center', zIndex: 50 },
      promotionDialog: { backgroundColor: '#1A2942', borderRadius: 20, padding: 24, width: 280 },
      promotionTitle: { fontSize: 18, fontWeight: 'bold', color: '#FFFFFF', textAlign: 'center', marginBottom: 16 },
      promotionOptions: { gap: 10 },
      promotionOption: { backgroundColor: '#4A90E2', borderRadius: 12, padding: 14, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 12 },
      promotionOptionText: { fontSize: 16, fontWeight: 'bold', color: '#FFFFFF' },
      graph: { backgroundColor: '#1A2740', borderRadius: 6, height: 60, whiteFill: 'rgba(255,255,255,0.25)', blackFill: 'rgba(0,0,0,0.35)', midStroke: 'rgba(255,255,255,0.15)', midStrokeWidth: 1, curveStroke: '#FDB022', curveStrokeWidth: 1.5, clampCp: 500 },
    };

  var BOARD = {
    referenceWidth: 390,
    referenceHeight: 844,
    referencePixelRatio: 3,
    boardSize: 389.3333333333333,
    squareSize: 48.666666666666664,
  };

  /** `floor(screenWidthPx / 8) * 8 / pixelRatio` — the source's own formula. */
  function boardSize(width, pixelRatio) {
    return (Math.floor(Math.round(width * pixelRatio) / 8) * 8) / pixelRatio;
  }

  /** Level -> the coach's accent colour, from the source's own `COACH_DATA`. */
  var ACCENTS = {
    "1": "#4CAF50",
    "2": "#E91E8C",
    "3": "#FF6B35",
    "4": "#FF9BC4",
    "5": "#FDB022"
  };

  /** The five coaches, verbatim from the source's own `COACH_DATA`. */
  var COACHES = [
    {
      "level": 1,
      "name": "Jaden Pogi",
      "role": "Young Pawn Hero",
      "tagline": "Friendly • Casual • Just having fun",
      "intro": "Hey! I'm Jaden Pogi. I'm still learning too — but I'll give it my best shot! Let's go! 😄",
      "thinkingMsg": "Umm... let me think for a sec... 🤔",
      "yourTurnMsg": "Your move! I'll try to keep up! 😅",
      "winMsg": "Hehe, I got you! Don't worry — you'll beat me next time! 😄",
      "loseMsg": "You won! Wow, you're so strong! 🎉 I still have a lot to learn!",
      "accentColor": "#4CAF50",
      "rating": 800
    },
    {
      "level": 2,
      "name": "Pretty Jade",
      "role": "Little Princess Gambit",
      "tagline": "Tricky • Unpredictable • Surprising",
      "intro": "Hi! I'm Pretty Jade ✨ I love sneaky moves — can you keep up with me? Hehe~",
      "thinkingMsg": "Planning something sneaky... ✨",
      "yourTurnMsg": "Your move~ don't fall into my trap! 💅",
      "winMsg": "Hehe~ my trap worked perfectly! Better luck next time! 💅",
      "loseMsg": "Oh no! You beat me! You're really good! ✨",
      "accentColor": "#E91E8C",
      "rating": 1500
    },
    {
      "level": 3,
      "name": "Handsome Jude",
      "role": "Kuya Tactician",
      "tagline": "Sharp • Aggressive • Tactical",
      "intro": "I'm Handsome Jude. My tactics are sharp and aggressive — ready for battle? ⚔️",
      "thinkingMsg": "Calculating the sharpest line... ⚔️",
      "yourTurnMsg": "Your move. Don't blunder — I'll punish it. 😤",
      "winMsg": "Tactics win games! You'll need to sharpen your calculation! ⚔️",
      "loseMsg": "You outplayed me! Respect — that was genuinely sharp. 👊",
      "accentColor": "#FF6B35",
      "rating": 1800
    },
    {
      "level": 4,
      "name": "Mommy Julie",
      "role": "Mommy Strategist",
      "tagline": "Calm • Positional • Patient",
      "intro": "Hello! I'm Mommy Julie. Good chess is about patience and solid positions. Let's play! 🌸",
      "thinkingMsg": "Finding the best positional move... 🌸",
      "yourTurnMsg": "Take your time, anak. Good moves need patience. 🌸",
      "winMsg": "Patience wins every time! Keep studying positions, anak! 🌸",
      "loseMsg": "Well played! You showed such great patience today. I'm proud! 🌸",
      "accentColor": "#FF9BC4",
      "rating": 2000
    },
    {
      "level": 5,
      "name": "Coach Pogi",
      "role": "The Master Trainer",
      "tagline": "Maximum strength • Full power • Unrelenting",
      "intro": "I'm Coach Pogi. I've mastered every position on this board. Show me what you've got. 👑",
      "thinkingMsg": "Analyzing at full depth... every line accounted for. 👑",
      "yourTurnMsg": "Your move. Every tempo matters at this level. 👑",
      "winMsg": "That's the gap in preparation. Study harder — I'll be here. 👑",
      "loseMsg": "You defeated me. Truly exceptional play today. 👑",
      "accentColor": "#FDB022",
      "rating": 2500
    }
  ];

  var COLOR_MAPS = {};

  /** Every scalar property of every block, as `--<prefix>-<block>-<prop>` custom properties. */
  var UNITLESS = {
    flex: 1, flexGrow: 1, flexShrink: 1, fontWeight: 1, opacity: 1, zIndex: 1,
    aspectRatio: 1, shadowOpacity: 1, elevation: 1,
  };
  function kebab(s) { return s.replace(/[A-Z]/g, function (c) { return '-' + c.toLowerCase(); }); }
  function cssVarName(prefix, block, prop) {
    return '--' + prefix + '-' + kebab(block) + '-' + kebab(prop);
  }
  function cssValue(prop, v) {
    if (typeof v === 'number') return UNITLESS[prop] ? String(v) : v + 'px';
    return String(v);
  }
  function applyAll(node, prefix, blocks) {
    Object.keys(blocks).forEach(function (block) {
      var b = blocks[block];
      if (!b) return;
      Object.keys(b).forEach(function (prop) {
        var v = b[prop];
        if (v === null || typeof v === 'object') return;
        node.style.setProperty(cssVarName(prefix, block, prop), cssValue(prop, v));
      });
    });
  }

  function selfTestSource(src) {
    var passed = 0, failures = [];
    function expect(c, what) { if (c) passed++; else failures.push(what); }
    var same = function (a, b) {
      if (a !== null && typeof a === 'object') return JSON.stringify(a) === JSON.stringify(b);
      return a === b;
    };
    var pairs = ["SELECT","PLAY"];
    var sheets = {
      SELECT: src.screens.coachSelect.styles,
      PLAY: src.screens.play.styles,
    };
    var mine = { SELECT: SELECT, PLAY: PLAY };
    var compared = 0;
    pairs.forEach(function (name) {
      var theirs = sheets[name], ours = mine[name];
      if (!theirs || !ours) return;
      Object.keys(theirs).forEach(function (block) {
        expect(ours[block] != null, name + '.' + block + ' is missing from the metrics layer');
        if (!ours[block]) return;
        Object.keys(theirs[block]).forEach(function (prop) {
          expect(same(ours[block][prop], theirs[block][prop]),
                 name + '.' + block + '.' + prop + ': metrics have '
                 + JSON.stringify(ours[block][prop]) + ', the RN source has '
                 + JSON.stringify(theirs[block][prop]));
          compared++;
        });
      });
    });
    expect(compared > 600,
           'only ' + compared + ' properties compared — the extraction probably moved');
    var gsvg = src.screens.evalGraph.svg;
    expect(PLAY.graph.backgroundColor === gsvg['Rect.fill'], 'the graph fill is the extracted one');
    expect(PLAY.graph.curveStroke === gsvg['Polyline.stroke'], 'and the curve colour');
    expect(PLAY.graph.clampCp === src.screens.evalGraph.moduleConstants.CLAMP,
           'and the clamp is the component CLAMP, not a second opinion');
    var data = src.screens.play.moduleConstants.COACH_DATA;
    expect(COACHES.length === 5, 'five coaches');
    COACHES.forEach(function (c) {
      var them = data[c.level];
      ['name', 'role', 'tagline', 'intro', 'thinkingMsg', 'yourTurnMsg', 'winMsg', 'loseMsg',
       'accentColor', 'rating'].forEach(function (f) {
        expect(c[f] === them[f], 'coach ' + c.level + '.' + f + ' matches COACH_DATA');
      });
    });
    for (var ci = 1; ci < COACHES.length; ci++) {
      expect(COACHES[ci].rating > COACHES[ci - 1].rating, 'ratings ascend by level');
    }
    var levels = Object.keys(ACCENTS);
    expect(levels.length === 5, 'five accent colours, one per coach');
    levels.forEach(function (lv) {
      expect(/^#[0-9A-Fa-f]{6}$/.test(ACCENTS[lv]), 'accent ' + lv + ' is a hex colour');
      expect(ACCENTS[lv] === src.screens.play.moduleConstants.COACH_DATA[lv].accentColor,
             'accent ' + lv + ' matches COACH_DATA');
    });
    expect(BOARD.squareSize * 8 === BOARD.boardSize, 'the board is eight squares wide');
    expect(boardSize(BOARD.referenceWidth, BOARD.referencePixelRatio) === BOARD.boardSize,
           'the formula reproduces the reference board size');

    return {
      passed: passed, failures: failures, ok: failures.length === 0,
      summary: failures.length === 0
        ? 'coach-metrics vs RN source: ' + passed + ' assertions passed'
        : 'coach-metrics vs RN source: ' + passed + ' passed, ' + failures.length + ' FAILED\n'
          + failures.slice(0, 20).map(function (f) { return '  x ' + f; }).join('\n'),
    };
  }

  return {
    SELECT: SELECT,
    PLAY: PLAY,
    BOARD: BOARD, COLOR_MAPS: COLOR_MAPS, ACCENTS: ACCENTS, COACHES: COACHES,
    boardSize: boardSize,
    cssVarName: cssVarName, cssValue: cssValue, applyAll: applyAll,
    selfTestSource: selfTestSource,
  };
})();

if (typeof module !== 'undefined' && module.exports) { module.exports = BiyaCoachMetrics; }
