/* opening-book.js — the bundled offline ECO opening book
 *
 * The browser mirror of Sources/BiyaherongCoachCore/OpeningBook.swift.
 *
 *     node -e "console.log(require('./web-demo/js/opening-book.js').selfTest().summary)"
 *
 * This replaces the original app's Lichess masters explorer, which cannot exist offline. The book is
 * generated by tools/eco/build_eco.php from lichess-org/chess-openings (CC0) and keyed by
 * `Engine.positionKey` — the 4-field FEN with a dead en-passant square cleared — so **transpositions
 * resolve**: reaching a position by a different move order finds the same entry.
 *
 * Two kinds of row, both "in book":
 *   named        — an ECO line ENDS here; carries an eco code and a name.
 *   pass-through — a line merely traverses here; the name is empty.
 * Only named rows change the displayed opening. A miss keeps the LAST known name, so a position
 * twenty moves into the Najdorf still reads "Najdorf" rather than going blank (spec Part 12.2).
 * Both kinds count as in-book, which is what makes the `book` classification tier meaningful.
 *
 * Classic script, no ES modules, so it runs from file:// on Windows.
 */
var BiyaOpeningBook = (function () {
  'use strict';

  var isNode = (typeof module !== 'undefined' && module.exports);
  var E = isNode ? require('./engine.js') : Engine;
  var DATA = isNode ? require('./eco-data.js') : ECO_DATA;

  /** Raw row for a position key, or null when the position is out of book. */
  function entry(key) {
    var row = DATA[key];
    if (!row) return null;
    return { eco: row[0], name: row[1] };
  }

  /** Is this position in the book at all? Pass-through rows count. Drives the `book` tier. */
  function contains(key) { return Object.prototype.hasOwnProperty.call(DATA, key); }

  /** The entry only when it actually carries a name; pass-through rows return null. */
  function named(key) {
    var e = entry(key);
    return (e && e.name !== '') ? e : null;
  }

  /**
   * The opening to display at this position. A named hit wins; anything else — a pass-through row or
   * a miss — keeps whatever was showing before.
   */
  function nameFor(key, lastKnown) {
    var e = named(key);
    return e ? e : (lastKnown || null);
  }

  /**
   * Every legal move from `pos` that lands on a book position, for the Opening Explorer panel.
   * Sorted by SAN so the list is deterministic in both languages.
   */
  function continuations(pos) {
    var out = [];
    var moves = E.legalMoves(pos);
    for (var i = 0; i < moves.length; i++) {
      var after = E.makeMove(pos, moves[i]);
      var key = E.positionKey(after);
      if (!contains(key)) continue;
      var e = entry(key);
      out.push({ san: E.san(pos, moves[i]), uci: E.moveUci(moves[i]), key: key,
                 eco: e.eco, name: e.name });
    }
    out.sort(function (a, b) { return a.san < b.san ? -1 : (a.san > b.san ? 1 : 0); });
    return out;
  }

  /**
   * Which plies of a game are still in book. `positionKeys[0]` is the start position, so the result
   * holds indices >= 1 — the same indices `moveEvaluations[].move_index` uses.
   */
  function bookPlies(positionKeys) {
    var out = [];
    for (var i = 1; i < positionKeys.length; i++) if (contains(positionKeys[i])) out.push(i);
    return out;
  }

  /** How many plies from the start the game stayed in book, stopping at the first miss. */
  function bookPrefixLength(positionKeys) {
    var n = 0;
    for (var i = 1; i < positionKeys.length; i++) {
      if (!contains(positionKeys[i])) break;
      n++;
    }
    return n;
  }

  function size() { return Object.keys(DATA).length; }

  // ---- Self-test ------------------------------------------------------------
  function selfTest() {
    var passed = 0, failures = [];
    function expect(cond, what) { cond ? passed++ : failures.push(what); }
    function keysFor(sans) {
      var pos = E.start(), out = [E.positionKey(pos)];
      for (var i = 0; i < sans.length; i++) {
        var m = E.parseSan(pos, sans[i]);
        if (!m) return null;
        pos = E.makeMove(pos, m);
        out.push(E.positionKey(pos));
      }
      return out;
    }
    function keyAfter(sans) { var k = keysFor(sans); return k ? k[k.length - 1] : null; }

    expect(size() > 7000, 'the book loaded (' + size() + ' positions)');

    // Named lookups.
    var e4 = named(keyAfter(['e4']));
    expect(e4 && e4.eco === 'B00' && e4.name === "King's Pawn Game", '1. e4 -> B00 King\'s Pawn Game');
    var sicilian = named(keyAfter(['e4', 'c5']));
    expect(sicilian && sicilian.eco === 'B20' && sicilian.name === 'Sicilian Defense', '1. e4 c5 -> B20 Sicilian');
    var ruy = named(keyAfter(['e4', 'e5', 'Nf3', 'Nc6', 'Bb5']));
    expect(ruy && ruy.eco === 'C60' && ruy.name === 'Ruy Lopez', 'Ruy Lopez');
    var najdorf = named(keyAfter(['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6']));
    expect(najdorf && najdorf.eco === 'B90' && najdorf.name.indexOf('Najdorf') >= 0, 'Najdorf');

    // Transpositions resolve — the whole reason the key clears a dead ep square.
    expect(keyAfter(['e4', 'e5', 'Nf3']) === keyAfter(['Nf3', 'e5', 'e4']),
      '1. e4 e5 2. Nf3 == 1. Nf3 e5 2. e4');
    expect(keyAfter(['d4', 'd5', 'c4']) === keyAfter(['c4', 'd5', 'd4']),
      '1. d4 d5 2. c4 == 1. c4 d5 2. d4');

    // Pass-through: in book, but carries no name of its own.
    var kid = keyAfter(['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7']);
    expect(contains(kid), 'a pass-through position is in book');
    expect(named(kid) === null, 'but it carries no name of its own');
    expect(nameFor(kid, ruy) === ruy, 'a pass-through keeps the last known opening');
    expect(nameFor('not a key at all', ruy) === ruy, 'a miss keeps the last known opening too');
    expect(nameFor('not a key at all', null) === null, 'with nothing known, a miss stays null');

    // Out of book.
    var silly = keyAfter(['a4', 'h5', 'Ra3', 'Rh6']);
    expect(!contains(silly), 'a nonsense line leaves the book');

    // Continuations.
    var fromStart = continuations(E.start());
    expect(fromStart.length > 15, 'the start position has many book continuations (' + fromStart.length + ')');
    var sans = fromStart.map(function (c) { return c.san; });
    expect(sans.indexOf('e4') >= 0 && sans.indexOf('d4') >= 0, 'e4 and d4 are book continuations');
    var sorted = sans.slice().sort();
    expect(sans.join(',') === sorted.join(','), 'continuations are sorted by SAN');
    var afterE4 = continuations(E.fromFEN(E.toFEN(E.makeMove(E.start(), E.parseSan(E.start(), 'e4')))));
    expect(afterE4.some(function (c) { return c.san === 'c5'; }), 'the Sicilian is a continuation of 1. e4');

    // Book plies and the prefix.
    var keys = keysFor(['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6']);
    expect(bookPlies(keys).length === 10, 'every ply of the Najdorf is in book');
    expect(bookPrefixLength(keys) === 10, 'the book prefix covers the whole line');
    var mixed = keysFor(['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7']);
    expect(bookPrefixLength(mixed) >= 6, 'a real opening stays in book for a while (' + bookPrefixLength(mixed) + ')');
    var leaves = keysFor(['a4', 'h5', 'Ra3', 'Rh6']);
    expect(bookPrefixLength(leaves) < 4, 'a nonsense line leaves book early');
    expect(bookPlies([keys[0]]).length === 0, 'a game with no moves has no book plies');

    return {
      passed: passed,
      failures: failures,
      ok: failures.length === 0,
      summary: failures.length === 0
        ? 'OpeningBookSelfTest: ' + passed + ' assertions passed'
        : 'OpeningBookSelfTest: ' + passed + ' passed, ' + failures.length + ' FAILED\n'
          + failures.map(function (x) { return '  ✗ ' + x; }).join('\n')
    };
  }

  return {
    entry: entry, contains: contains, named: named, nameFor: nameFor,
    continuations: continuations, bookPlies: bookPlies, bookPrefixLength: bookPrefixLength,
    size: size, selfTest: selfTest
  };
})();

/* Makes the book runnable headlessly under Node without changing the browser behaviour. */
if (typeof module !== 'undefined' && module.exports) { module.exports = BiyaOpeningBook; }
