/* GENERATED by tools/metrics/gen_video_metrics.js — DO NOT HAND-EDIT.
 *
 * Every number, colour and category glyph the Tutorial Videos screens draw, from
 * tools/metrics/video_styles.json, which extract_video_styles.js re-derives from the
 * React Native source. Nothing here is transcribed.
 *
 * The COPY is not here — see VideoStrings, which is hand-written and pinned by
 * tools/qa/replay_videos.js. The RN keeps its strings in JSX rather than in a table, and
 * this app says things the RN never had to: it can be offline, and the RN could not.
 */
var BiyaVideoMetrics = (function () {
  'use strict';

  var LIST = {
    container: { flex: 1, backgroundColor: '#0F1A2E' },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#1A2942' },
    backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
    backIcon: { fontSize: 26, color: '#FFFFFF' },
    headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#FFFFFF' },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    loadingText: { marginTop: 12, fontSize: 14, color: '#8BA3C7' },
    emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 40 },
    emptyIcon: { fontSize: 48, marginBottom: 16 },
    emptyTitle: { fontSize: 22, fontWeight: 'bold', color: '#FFFFFF', marginBottom: 8 },
    emptySubtitle: { fontSize: 14, color: '#8BA3C7', textAlign: 'center' },
    paywallContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 40 },
    paywallIcon: { fontSize: 56, marginBottom: 20 },
    paywallLabel: { fontSize: 22, fontWeight: 'bold', color: '#FDB022', marginBottom: 16 },
    paywallMessage: { fontSize: 16, color: '#FFFFFF', textAlign: 'center', marginBottom: 10, lineHeight: 24 },
    paywallSubtext: { fontSize: 13, color: '#8BA3C7', textAlign: 'center', marginBottom: 32, lineHeight: 20 },
    subscribeButton: { backgroundColor: '#FDB022', borderRadius: 12, paddingVertical: 14, paddingHorizontal: 40 },
    subscribeButtonText: { color: '#0F1A2E', fontSize: 16, fontWeight: 'bold' },
    listContent: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 28 },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', marginTop: 20, marginBottom: 10, gap: 8 },
    sectionAccent: { width: 3, height: 18, borderRadius: 2 },
    sectionTitle: { fontSize: 15, fontWeight: '700', flex: 1 },
    sectionCount: { fontSize: 11, color: '#5A7A9A', fontWeight: '500' },
    videoCard: { flexDirection: 'row', backgroundColor: '#162136', borderRadius: 14, overflow: 'hidden', marginBottom: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)', elevation: 3, shadowColor: '#000', shadowOffset: {"width":0,"height":2}, shadowOpacity: 0.2, shadowRadius: 4 },
    thumbWrap: { backgroundColor: '#0D1520', position: 'relative', flexShrink: 0 },
    thumb: { width: '100%', height: '100%' },
    playOverlay: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.28)' },
    playBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(253,176,34,0.92)', justifyContent: 'center', alignItems: 'center' },
    playBtnIcon: { fontSize: 14, color: '#FFFFFF', marginLeft: 2 },
    cardInfo: { flex: 1, padding: 12, justifyContent: 'center', gap: 6 },
    catChip: { alignSelf: 'flex-start', borderRadius: 6, paddingVertical: 3, paddingHorizontal: 8 },
    catChipText: { fontSize: 10, fontWeight: '700', letterSpacing: 0.3 },
    cardTitle: { fontSize: 14, fontWeight: '700', color: '#FFFFFF', lineHeight: 19 },
    cardDesc: { fontSize: 12, color: '#7A9AB8', lineHeight: 17 },
    cardDate: { fontSize: 10, color: '#4A6A8A', marginTop: 2 },
  };

  var PLAY = {
    root: { flex: 1, backgroundColor: '#000' },
    topBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingBottom: 12, gap: 8, backgroundColor: 'rgba(0,0,0,0.55)' },
    backBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)', justifyContent: 'center', alignItems: 'center' },
    backIcon: { fontSize: 22, color: '#FFFFFF', fontWeight: 'bold' },
    titleText: { flex: 1, fontSize: 15, fontWeight: '600', color: '#FFFFFF' },
    fullscreenBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.15)', justifyContent: 'center', alignItems: 'center' },
    middleArea: { flex: 1 },
    controlBar: { backgroundColor: 'rgba(15,26,46,0.92)', paddingHorizontal: 16, paddingTop: 12, gap: 6, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.08)' },
    seekRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    timeText: { fontSize: 12, color: '#8BA3C7', minWidth: 38 },
    timeRight: { textAlign: 'right' },
    seekTrackContainer: { flex: 1, justifyContent: 'center' },
    trackBg: { position: 'absolute', left: 0, right: 0, backgroundColor: 'rgba(255,255,255,0.25)' },
    trackFill: { position: 'absolute', left: 0, backgroundColor: '#FDB022' },
    trackThumb: { position: 'absolute', backgroundColor: '#FDB022', shadowColor: '#FDB022', shadowOpacity: 0.7, shadowRadius: 4, elevation: 4 },
    buttonsRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 24, paddingVertical: 4 },
    seekBtn: { alignItems: 'center', padding: 8, minWidth: 56 },
    seekIcon: { fontSize: 26, color: '#FFFFFF' },
    seekLabel: { fontSize: 11, color: '#8BA3C7', marginTop: 2 },
    playPauseBtn: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#FDB022', justifyContent: 'center', alignItems: 'center' },
    playPauseIcon: { fontSize: 24, color: '#0F1A2E' },
  };

  /* What each section looks like. The ORDER lives in the Core (VideoLibrary.categoryOrder) and in
     web-demo/js/video-library.js, because grouping is domain logic; this table is only its skin. */
  var CATEGORIES = {
    'Opening': { accent: '#7BB3F0', chipBackground: '#1D3461', glyph: '📖' },
    'Middlegame': { accent: '#A78BFA', chipBackground: '#2D1B69', glyph: '⚔️' },
    'Endgame': { accent: '#FDB022', chipBackground: '#3B2200', glyph: '👑' },
    'General': { accent: '#5CC264', chipBackground: '#1A3320', glyph: '♟️' },
    'Uncategorized': { accent: '#8BA3C7', chipBackground: '#1A2942', glyph: '📂' },
  };

  /** An unknown category never reaches here — VideoLibrary.categoryKey folds it to Uncategorized
      first — but the fallback keeps a missing entry from rendering as `undefined`. */
  function categoryMeta(name) {
    return CATEGORIES[name] || CATEGORIES['Uncategorized'];
  }

  var API = {
    LIST: LIST, PLAY: PLAY, CATEGORIES: CATEGORIES, categoryMeta: categoryMeta,
    THUMB_W: 90,
    THUMB_H: 160
  };

  return API;
})();

if (typeof module !== 'undefined' && module.exports) { module.exports = BiyaVideoMetrics; }
