// GENERATED by tools/metrics/gen_coach_metrics.js — DO NOT HAND-EDIT.
//
// Twin of `web-demo/js/coach-metrics.js`. Both are emitted from
// `tools/metrics/coach_styles.json`, which `extract_coach_styles.js` re-derives from the React
// Native source on every run — so these are not two transcriptions of a third thing, they are two
// renderings of one.
//
// **No numeric literal and no arithmetic in any view body.** Every number a Play vs Coach screen
// draws is a stored property here. Break that and the coverage drains out silently.
//
// `CoachStrings` is NOT generated here: copy comes from spec 2.14 and has to be transcribed before
// it can be emitted.

import SwiftUI

/// Extracted from app/(app)/user/play-coach/index.tsx.
public enum CoachSelect {
    public static let containerFlex: CGFloat = 1
    public static let containerBackgroundColor = Theme.c(0x070E20)
    public static let bgGlowAPosition = "absolute"
    public static let bgGlowAWidth: CGFloat = 585
    public static let bgGlowAHeight: CGFloat = 585
    public static let bgGlowABorderRadius: CGFloat = 292.5
    public static let bgGlowABackgroundColor = Theme.c(0x0050C8, 0.16)
    public static let bgGlowABottom: CGFloat = -280.8
    public static let bgGlowALeft: CGFloat = -97.5
    public static let bgGlowBPosition = "absolute"
    public static let bgGlowBWidth: CGFloat = 380.25
    public static let bgGlowBHeight: CGFloat = 380.25
    public static let bgGlowBBorderRadius: CGFloat = 190.125
    public static let bgGlowBBackgroundColor = Theme.c(0x008CFF, 0.1)
    public static let bgGlowBBottom: CGFloat = -128.7
    public static let bgGlowBLeft: CGFloat = 4.875
    public static let scrollPaddingBottom: CGFloat = 36
    public static let backBtnWidth: CGFloat = 44
    public static let backBtnHeight: CGFloat = 44
    public static let backBtnJustifyContent = "center"
    public static let backBtnAlignItems = "center"
    public static let backBtnMarginTop: CGFloat = 8
    public static let backBtnMarginLeft: CGFloat = 10
    public static let backIconFontSize: CGFloat = 26
    public static let backIconColor = Theme.c(0xFFFFFF)
    public static let titleBlockAlignItems = "center"
    public static let titleBlockPaddingHorizontal: CGFloat = 24
    public static let titleBlockPaddingBottom: CGFloat = 22
    public static let titleBlockPaddingTop: CGFloat = 4
    public static let titleTopRowFlexDirection = "row"
    public static let titleTopRowAlignItems = "center"
    public static let titleTopRowMarginBottom: CGFloat = 4
    public static let knightDecorFontSize: CGFloat = 16
    public static let knightDecorColor = Theme.c(0xFFFFFF)
    public static let knightDecorOpacity: CGFloat = 0.85
    public static let titleSmallFontSize: CGFloat = 12
    public static let titleSmallFontWeight = "700"
    public static let titleSmallColor = Theme.c(0xFFFFFF)
    public static let titleSmallLetterSpacing: CGFloat = 2
    public static let titleLargeFontSize: CGFloat = 30
    public static let titleLargeFontWeight = "900"
    public static let titleLargeColor = Theme.c(0xFDB022)
    public static let titleLargeTextAlign = "center"
    public static let titleLargeLineHeight: CGFloat = 35
    public static let titleLargeLetterSpacing: CGFloat = 0.8
    public static let titleLargeTextTransform = "uppercase"
    public static let chessPieceAccentFontSize: CGFloat = 22
    public static let chessPieceAccentColor = Theme.c(0xFDB022)
    public static let chessPieceAccentMarginTop: CGFloat = 2
    public static let chessPieceAccentMarginBottom: CGFloat = 2
    public static let titleSubFontSize: CGFloat = 13
    public static let titleSubColor = Theme.c(0xFFFFFF, 0.85)
    public static let titleSubMarginTop: CGFloat = 6
    public static let titleSubTextAlign = "center"
    public static let titleSubLineHeight: CGFloat = 18
    public static let row1FlexDirection = "row"
    public static let row1JustifyContent = "space-around"
    public static let row1AlignItems = "flex-end"
    public static let row1PaddingHorizontal: CGFloat = 4
    public static let row1MarginBottom: CGFloat = 6
    public static let row2FlexDirection = "row"
    public static let row2JustifyContent = "center"
    public static let row2AlignItems = "flex-end"
    public static let row2PaddingHorizontal: CGFloat = 31.2
    public static let row2Gap: CGFloat = 16
    public static let row2MarginBottom: CGFloat = 22
    public static let coachCardFlex: CGFloat = 1
    public static let coachCardAlignItems = "center"
    public static let coachCardPaddingHorizontal: CGFloat = 4
    public static let coachCardPaddingBottom: CGFloat = 4
    public static let coachCardFeaturedFlex: CGFloat = 1.15
    public static let glowHaloJustifyContent = "center"
    public static let glowHaloAlignItems = "center"
    public static let glowHaloBackgroundColor = Theme.c(0x00A0FF, 0.07)
    public static let glowHaloMarginBottom: CGFloat = 8
    public static let glowHaloFeaturedBackgroundColor = Theme.c(0x00C8FF, 0.1)
    public static let glowHaloLockedBackgroundColor = Theme.c(0x505050, 0.07)
    public static let cyanRingJustifyContent = "center"
    public static let cyanRingAlignItems = "center"
    public static let cyanRingBorderWidth: CGFloat = 2.5
    public static let cyanRingBorderColor = Theme.c(0x00DCFF, 0.95)
    public static let cyanRingBackgroundColor = Theme.c(0x04143C, 0.5)
    public static let cyanRingShadowColor = Theme.c(0x00CFFF)
    public static let cyanRingShadowOffsetWidth: CGFloat = 0
    public static let cyanRingShadowOffsetHeight: CGFloat = 0
    public static let cyanRingShadowOpacity: CGFloat = 0.9
    public static let cyanRingShadowRadius: CGFloat = 8
    public static let cyanRingElevation: CGFloat = 6
    public static let cyanRingFeaturedBorderWidth: CGFloat = 3
    public static let cyanRingFeaturedBorderColor = Theme.c(0x00E5FF)
    public static let cyanRingFeaturedShadowRadius: CGFloat = 14
    public static let cyanRingFeaturedShadowOpacity: CGFloat = 1
    public static let cyanRingLockedBorderColor = Theme.c(0x787878, 0.5)
    public static let cyanRingLockedShadowOpacity: CGFloat = 0.2
    public static let lockOverlayPosition = "absolute"
    public static let lockOverlayJustifyContent = "center"
    public static let lockOverlayAlignItems = "center"
    public static let lockOverlayBackgroundColor = Theme.c(0x000000, 0.35)
    public static let lockIconFontSize: CGFloat = 22
    public static let premiumTagBackgroundColor = Theme.c(0xFDB022, 0.15)
    public static let premiumTagBorderRadius: CGFloat = 8
    public static let premiumTagPaddingHorizontal: CGFloat = 8
    public static let premiumTagPaddingVertical: CGFloat = 3
    public static let premiumTagBorderWidth: CGFloat = 1
    public static let premiumTagBorderColor = Theme.c(0xFDB022)
    public static let premiumTagMarginTop: CGFloat = 2
    public static let premiumTagTextFontSize: CGFloat = 9
    public static let premiumTagTextColor = Theme.c(0xFDB022)
    public static let premiumTagTextFontWeight = "700"
    public static let premiumTagTextLetterSpacing: CGFloat = 0.5
    public static let coachNameFontSize: CGFloat = 13
    public static let coachNameFontWeight = "700"
    public static let coachNameColor = Theme.c(0xFFFFFF)
    public static let coachNameTextAlign = "center"
    public static let coachNameMarginBottom: CGFloat = 1
    public static let coachNameFeaturedFontSize: CGFloat = 16
    public static let coachNameFeaturedFontWeight = "900"
    public static let coachNameLockedColor = Theme.c(0xFFFFFF, 0.45)
    public static let coachRoleFontSize: CGFloat = 10
    public static let coachRoleColor = Theme.c(0xFDB022)
    public static let coachRoleTextAlign = "center"
    public static let coachRoleFontWeight = "600"
    public static let coachRoleFeaturedFontSize: CGFloat = 12
    public static let coachRatingFontSize: CGFloat = 10
    public static let coachRatingColor = Theme.c(0x8BA3C7)
    public static let coachRatingFontWeight = "700"
    public static let coachRatingTextAlign = "center"
    public static let coachRatingMarginTop: CGFloat = 1
    public static let coachRatingFeaturedFontSize: CGFloat = 12
    public static let coachRatingFeaturedColor = Theme.c(0xFDB022)
    public static let coachDescFontSize: CGFloat = 9
    public static let coachDescColor = Theme.c(0xFFFFFF, 0.55)
    public static let coachDescTextAlign = "center"
    public static let coachDescMarginTop: CGFloat = 1
    public static let settingsRowFlexDirection = "row"
    public static let settingsRowAlignItems = "center"
    public static let settingsRowJustifyContent = "space-between"
    public static let settingsRowMarginHorizontal: CGFloat = 24
    public static let settingsRowMarginBottom: CGFloat = 18
    public static let settingsRowBackgroundColor = Theme.c(0xFFFFFF, 0.06)
    public static let settingsRowBorderRadius: CGFloat = 14
    public static let settingsRowPaddingHorizontal: CGFloat = 18
    public static let settingsRowPaddingVertical: CGFloat = 12
    public static let settingsRowBorderWidth: CGFloat = 1
    public static let settingsRowBorderColor = Theme.c(0xFFFFFF, 0.08)
    public static let settingsLabelFontSize: CGFloat = 14
    public static let settingsLabelFontWeight = "700"
    public static let settingsLabelColor = Theme.c(0xFFFFFF)
    public static let footerAlignItems = "center"
    public static let footerPaddingHorizontal: CGFloat = 20
    public static let footerPaddingTop: CGFloat = 4
    public static let footerBoldFontSize: CGFloat = 21
    public static let footerBoldFontWeight = "900"
    public static let footerBoldColor = Theme.c(0xFDB022)
    public static let footerBoldTextAlign = "center"
    public static let footerBoldMarginBottom: CGFloat = 5
    public static let footerLightFontSize: CGFloat = 12
    public static let footerLightColor = Theme.c(0xFFFFFF, 0.65)
    public static let footerLightFontStyle = "italic"
    public static let footerLightTextAlign = "center"
    public static let footerLightLetterSpacing: CGFloat = 1.5
    public static let cardSizeAvatarRegular: CGFloat = 80
    public static let cardSizeRingRegular: CGFloat = 86
    public static let cardSizeHaloRegular: CGFloat = 96
    public static let cardSizeAvatarFeatured: CGFloat = 108
    public static let cardSizeRingFeatured: CGFloat = 114
    public static let cardSizeHaloFeatured: CGFloat = 124
}

/// Extracted from app/(app)/user/play-coach/play.tsx.
public enum CoachPlay {
    public static let containerFlex: CGFloat = 1
    public static let containerBackgroundColor = Theme.c(0x07111F)
    public static let backBtnWidth: CGFloat = 44
    public static let backBtnHeight: CGFloat = 44
    public static let backBtnJustifyContent = "center"
    public static let backBtnAlignItems = "center"
    public static let backIconFontSize: CGFloat = 26
    public static let backIconColor = Theme.c(0xFFFFFF)
    public static let selTopGlowPosition = "absolute"
    public static let selTopGlowTop: CGFloat = 0
    public static let selTopGlowLeft: CGFloat = 0
    public static let selTopGlowRight: CGFloat = 0
    public static let selTopGlowHeight: CGFloat = 429.00000000000006
    public static let selTopGlowBorderBottomLeftRadius: CGFloat = 214.50000000000003
    public static let selTopGlowBorderBottomRightRadius: CGFloat = 214.50000000000003
    public static let selScrollPaddingBottom: CGFloat = 36
    public static let selIntroBlockAlignItems = "center"
    public static let selIntroBlockPaddingHorizontal: CGFloat = 24
    public static let selIntroBlockPaddingTop: CGFloat = 4
    public static let selIntroBlockPaddingBottom: CGFloat = 18
    public static let selHaloWidth: CGFloat = 136
    public static let selHaloHeight: CGFloat = 136
    public static let selHaloBorderRadius: CGFloat = 68
    public static let selHaloJustifyContent = "center"
    public static let selHaloAlignItems = "center"
    public static let selHaloBackgroundColor = Theme.c(0x000000, 0.15)
    public static let selHaloShadowOffsetWidth: CGFloat = 0
    public static let selHaloShadowOffsetHeight: CGFloat = 0
    public static let selHaloShadowOpacity: CGFloat = 0.45
    public static let selHaloShadowRadius: CGFloat = 22
    public static let selHaloElevation: CGFloat = 10
    public static let selHaloMarginBottom: CGFloat = 10
    public static let selRingWidth: CGFloat = 120
    public static let selRingHeight: CGFloat = 120
    public static let selRingBorderRadius: CGFloat = 60
    public static let selRingBorderWidth: CGFloat = 3
    public static let selRingJustifyContent = "center"
    public static let selRingAlignItems = "center"
    public static let selRingBackgroundColor = Theme.c(0x041030, 0.65)
    public static let selRingShadowOffsetWidth: CGFloat = 0
    public static let selRingShadowOffsetHeight: CGFloat = 0
    public static let selRingShadowOpacity: CGFloat = 0.9
    public static let selRingShadowRadius: CGFloat = 14
    public static let selRingElevation: CGFloat = 8
    public static let selAvatarImgWidth: CGFloat = 112
    public static let selAvatarImgHeight: CGFloat = 112
    public static let selAvatarImgBorderRadius: CGFloat = 56
    public static let starsRowFlexDirection = "row"
    public static let starsRowGap: CGFloat = 5
    public static let starsRowMarginBottom: CGFloat = 8
    public static let starFontSize: CGFloat = 22
    public static let selNameFontSize: CGFloat = 27
    public static let selNameFontWeight = "900"
    public static let selNameColor = Theme.c(0xFFFFFF)
    public static let selNameTextAlign = "center"
    public static let selNameMarginBottom: CGFloat = 3
    public static let selRoleFontSize: CGFloat = 14
    public static let selRoleFontWeight = "700"
    public static let selRoleTextAlign = "center"
    public static let selRoleMarginBottom: CGFloat = 4
    public static let selTaglineFontSize: CGFloat = 11
    public static let selTaglineColor = Theme.c(0xFFFFFF, 0.4)
    public static let selTaglineTextAlign = "center"
    public static let selTaglineLetterSpacing: CGFloat = 0.3
    public static let selTaglineMarginBottom: CGFloat = 10
    public static let selRatingBadgeFlexDirection = "row"
    public static let selRatingBadgeAlignItems = "center"
    public static let selRatingBadgeGap: CGFloat = 6
    public static let selRatingBadgeBackgroundColor = Theme.c(0xFFFFFF, 0.06)
    public static let selRatingBadgeBorderRadius: CGFloat = 12
    public static let selRatingBadgePaddingHorizontal: CGFloat = 14
    public static let selRatingBadgePaddingVertical: CGFloat = 5
    public static let selRatingBadgeMarginBottom: CGFloat = 14
    public static let selRatingBadgeBorderWidth: CGFloat = 1
    public static let selRatingBadgeBorderColor = Theme.c(0xFFFFFF, 0.1)
    public static let selRatingLabelFontSize: CGFloat = 11
    public static let selRatingLabelFontWeight = "700"
    public static let selRatingLabelColor = Theme.c(0xFFFFFF, 0.45)
    public static let selRatingLabelLetterSpacing: CGFloat = 1
    public static let selRatingValueFontSize: CGFloat = 16
    public static let selRatingValueFontWeight = "900"
    public static let selRatingValueLetterSpacing: CGFloat = 0.5
    public static let selBubbleWrapWidth = "100%"
    public static let selBubbleWrapAlignItems = "center"
    public static let selTriangleWidth: CGFloat = 0
    public static let selTriangleHeight: CGFloat = 0
    public static let selTriangleBorderLeftWidth: CGFloat = 11
    public static let selTriangleBorderRightWidth: CGFloat = 11
    public static let selTriangleBorderBottomWidth: CGFloat = 14
    public static let selTriangleBorderLeftColor = Color.clear
    public static let selTriangleBorderRightColor = Color.clear
    public static let selTriangleMarginBottom: CGFloat = -1
    public static let selBubbleWidth = "100%"
    public static let selBubbleBackgroundColor = Theme.c(0x081432, 0.97)
    public static let selBubbleBorderRadius: CGFloat = 18
    public static let selBubbleBorderWidth: CGFloat = 1
    public static let selBubblePaddingHorizontal: CGFloat = 20
    public static let selBubblePaddingVertical: CGFloat = 16
    public static let selBubbleTextFontSize: CGFloat = 13
    public static let selBubbleTextColor = Theme.c(0xD4E8F8)
    public static let selBubbleTextLineHeight: CGFloat = 21
    public static let selBubbleTextFontStyle = "italic"
    public static let selBubbleTextTextAlign = "center"
    public static let colorSectionPaddingHorizontal: CGFloat = 20
    public static let colorSectionPaddingBottom: CGFloat = 16
    public static let colorSectionGap: CGFloat = 14
    public static let colorLabelFontSize: CGFloat = 14
    public static let colorLabelFontWeight = "700"
    public static let colorLabelColor = Theme.c(0xFFFFFF)
    public static let colorLabelTextAlign = "center"
    public static let colorLabelLetterSpacing: CGFloat = 1
    public static let colorLabelOpacity: CGFloat = 0.9
    public static let colorRowFlexDirection = "row"
    public static let colorRowGap: CGFloat = 12
    public static let colorCardFlex: CGFloat = 1
    public static let colorCardBorderRadius: CGFloat = 20
    public static let colorCardPaddingVertical: CGFloat = 24
    public static let colorCardAlignItems = "center"
    public static let colorCardGap: CGFloat = 6
    public static let colorCardBorderWidth: CGFloat = 2
    public static let colorCardWhiteBackgroundColor = Theme.c(0xEFF3F8)
    public static let colorCardWhiteBorderColor = Theme.c(0xCBD5E1)
    public static let colorCardBlackBackgroundColor = Theme.c(0x0F1520)
    public static let colorCardBlackBorderColor = Theme.c(0x2C3A50)
    public static let kingWFontSize: CGFloat = 44
    public static let kingWColor = Theme.c(0x1E293B)
    public static let colorNameWFontSize: CGFloat = 17
    public static let colorNameWFontWeight = "800"
    public static let colorNameWColor = Theme.c(0x1E293B)
    public static let colorHintWFontSize: CGFloat = 11
    public static let colorHintWColor = Theme.c(0x64748B)
    public static let kingBFontSize: CGFloat = 44
    public static let kingBColor = Theme.c(0xFFFFFF)
    public static let colorNameBFontSize: CGFloat = 17
    public static let colorNameBFontWeight = "800"
    public static let colorNameBColor = Theme.c(0xFFFFFF)
    public static let colorHintBFontSize: CGFloat = 11
    public static let colorHintBColor = Theme.c(0x94A3B8)
    public static let savedGameBannerMarginHorizontal: CGFloat = 20
    public static let savedGameBannerMarginTop: CGFloat = 4
    public static let savedGameBannerMarginBottom: CGFloat = 8
    public static let savedGameBannerFlexDirection = "row"
    public static let savedGameBannerAlignItems = "center"
    public static let savedGameBannerGap: CGFloat = 8
    public static let savedGameBannerBackgroundColor = Theme.c(0xFDB022, 0.1)
    public static let savedGameBannerBorderRadius: CGFloat = 12
    public static let savedGameBannerBorderWidth: CGFloat = 1
    public static let savedGameBannerBorderColor = Theme.c(0xFDB022, 0.35)
    public static let savedGameBannerPaddingHorizontal: CGFloat = 14
    public static let savedGameBannerPaddingVertical: CGFloat = 10
    public static let savedGameIconFontSize: CGFloat = 16
    public static let savedGameTextFlex: CGFloat = 1
    public static let savedGameTextFontSize: CGFloat = 12
    public static let savedGameTextColor = Theme.c(0xFDB022, 0.9)
    public static let savedGameTextFontWeight = "600"
    public static let playHeaderFlexDirection = "row"
    public static let playHeaderAlignItems = "center"
    public static let playHeaderPaddingHorizontal: CGFloat = 10
    public static let playHeaderPaddingTop: CGFloat = 6
    public static let playHeaderPaddingBottom: CGFloat = 6
    public static let playHeaderCenterFlex: CGFloat = 1
    public static let playHeaderCenterFlexDirection = "row"
    public static let playHeaderCenterAlignItems = "center"
    public static let playHeaderCenterJustifyContent = "center"
    public static let playHeaderCenterGap: CGFloat = 10
    public static let headerAvatarRingWidth: CGFloat = 42
    public static let headerAvatarRingHeight: CGFloat = 42
    public static let headerAvatarRingBorderRadius: CGFloat = 21
    public static let headerAvatarRingBorderWidth: CGFloat = 2
    public static let headerAvatarRingJustifyContent = "center"
    public static let headerAvatarRingAlignItems = "center"
    public static let headerAvatarRingOverflow = "hidden"
    public static let headerAvatarImgWidth: CGFloat = 38
    public static let headerAvatarImgHeight: CGFloat = 38
    public static let headerAvatarImgBorderRadius: CGFloat = 19
    public static let headerNameFontSize: CGFloat = 15
    public static let headerNameFontWeight = "800"
    public static let headerNameColor = Theme.c(0xFFFFFF)
    public static let headerRoleFontSize: CGFloat = 11
    public static let headerRoleFontWeight = "600"
    public static let headerRoleMarginTop: CGFloat = 1
    public static let colorBadgePaddingHorizontal: CGFloat = 10
    public static let colorBadgePaddingVertical: CGFloat = 5
    public static let colorBadgeBorderRadius: CGFloat = 12
    public static let colorBadgeMinWidth: CGFloat = 74
    public static let colorBadgeAlignItems = "center"
    public static let colorBadgeWBackgroundColor = Theme.c(0xFFFFFF, 0.1)
    public static let colorBadgeWBorderWidth: CGFloat = 1
    public static let colorBadgeWBorderColor = Theme.c(0xFFFFFF, 0.28)
    public static let colorBadgeBBackgroundColor = Theme.c(0x000000, 0.3)
    public static let colorBadgeBBorderWidth: CGFloat = 1
    public static let colorBadgeBBorderColor = Theme.c(0xFFFFFF, 0.15)
    public static let colorBadgeTextFontSize: CGFloat = 11
    public static let colorBadgeTextFontWeight = "600"
    public static let colorBadgeTextColor = Theme.c(0xFFFFFF)
    public static let talkStripFlexDirection = "row"
    public static let talkStripAlignItems = "center"
    public static let talkStripBackgroundColor = Theme.c(0xFFFFFF, 0.04)
    public static let talkStripMarginHorizontal: CGFloat = 12
    public static let talkStripMarginBottom: CGFloat = 4
    public static let talkStripBorderRadius: CGFloat = 14
    public static let talkStripPaddingHorizontal: CGFloat = 12
    public static let talkStripPaddingVertical: CGFloat = 8
    public static let talkStripBorderWidth: CGFloat = 1
    public static let talkStripGap: CGFloat = 10
    public static let talkStripMinHeight: CGFloat = 50
    public static let talkAvatarRingWidth: CGFloat = 40
    public static let talkAvatarRingHeight: CGFloat = 40
    public static let talkAvatarRingBorderRadius: CGFloat = 20
    public static let talkAvatarRingBorderWidth: CGFloat = 2
    public static let talkAvatarRingJustifyContent = "center"
    public static let talkAvatarRingAlignItems = "center"
    public static let talkAvatarRingFlexShrink: CGFloat = 0
    public static let talkAvatarRingOverflow = "hidden"
    public static let talkAvatarImgWidth: CGFloat = 36
    public static let talkAvatarImgHeight: CGFloat = 36
    public static let talkAvatarImgBorderRadius: CGFloat = 18
    public static let talkRightFlex: CGFloat = 1
    public static let talkRightFlexDirection = "row"
    public static let talkRightAlignItems = "center"
    public static let talkRightGap: CGFloat = 8
    public static let talkSpinnerFlexShrink: CGFloat = 0
    public static let talkTextFlex: CGFloat = 1
    public static let talkTextFontSize: CGFloat = 12
    public static let talkTextColor = Theme.c(0xFFFFFF, 0.78)
    public static let talkTextFontStyle = "italic"
    public static let talkTextLineHeight: CGFloat = 18
    public static let premoveChipBackgroundColor = Theme.c(0xFFC107, 0.2)
    public static let premoveChipBorderRadius: CGFloat = 8
    public static let premoveChipPaddingHorizontal: CGFloat = 8
    public static let premoveChipPaddingVertical: CGFloat = 4
    public static let premoveChipBorderWidth: CGFloat = 1
    public static let premoveChipBorderColor = Theme.c(0xFFC107, 0.5)
    public static let premoveChipTextFontSize: CGFloat = 10
    public static let premoveChipTextFontWeight = "700"
    public static let premoveChipTextColor = Theme.c(0xFDB022)
    public static let gameOverChipPaddingHorizontal: CGFloat = 12
    public static let gameOverChipPaddingVertical: CGFloat = 6
    public static let gameOverChipBorderRadius: CGFloat = 10
    public static let gameOverChipFlexShrink: CGFloat = 0
    public static let gameOverChipTextFontSize: CGFloat = 11
    public static let gameOverChipTextFontWeight = "800"
    public static let gameOverChipTextColor = Theme.c(0xFFFFFF)
    public static let modalOverlayFlex: CGFloat = 1
    public static let modalOverlayBackgroundColor = Theme.c(0x000000, 0.7)
    public static let modalOverlayJustifyContent = "center"
    public static let modalOverlayAlignItems = "center"
    public static let modalCardBackgroundColor = Theme.c(0x0D1B30)
    public static let modalCardBorderRadius: CGFloat = 22
    public static let modalCardPaddingVertical: CGFloat = 24
    public static let modalCardPaddingHorizontal: CGFloat = 28
    public static let modalCardAlignItems = "center"
    public static let modalCardWidth: CGFloat = 334
    public static let modalCardBorderWidth: CGFloat = 1
    public static let modalCardGap: CGFloat = 6
    public static let modalAvatarRingWidth: CGFloat = 68
    public static let modalAvatarRingHeight: CGFloat = 68
    public static let modalAvatarRingBorderRadius: CGFloat = 34
    public static let modalAvatarRingBorderWidth: CGFloat = 3
    public static let modalAvatarRingJustifyContent = "center"
    public static let modalAvatarRingAlignItems = "center"
    public static let modalAvatarRingOverflow = "hidden"
    public static let modalAvatarRingMarginBottom: CGFloat = 4
    public static let modalAvatarImgWidth: CGFloat = 60
    public static let modalAvatarImgHeight: CGFloat = 60
    public static let modalAvatarImgBorderRadius: CGFloat = 30
    public static let modalResultEmojiFontSize: CGFloat = 32
    public static let modalResultLabelFontSize: CGFloat = 22
    public static let modalResultLabelFontWeight = "900"
    public static let modalResultLabelTextAlign = "center"
    public static let modalResultTextFontSize: CGFloat = 13
    public static let modalResultTextFontWeight = "600"
    public static let modalResultTextTextAlign = "center"
    public static let modalResultTextLineHeight: CGFloat = 20
    public static let modalResultTextPaddingHorizontal: CGFloat = 4
    public static let modalResultTextOpacity: CGFloat = 0.85
    public static let modalActionsFlexDirection = "row"
    public static let modalActionsGap: CGFloat = 10
    public static let modalActionsMarginTop: CGFloat = 10
    public static let modalBtnPaddingHorizontal: CGFloat = 24
    public static let modalBtnPaddingVertical: CGFloat = 11
    public static let modalBtnBorderRadius: CGFloat = 14
    public static let modalBtnMinWidth: CGFloat = 100
    public static let modalBtnAlignItems = "center"
    public static let modalBtnTextFontSize: CGFloat = 14
    public static let modalBtnTextFontWeight = "800"
    public static let modalBtnTextColor = Theme.c(0xFFFFFF)
    public static let modalBtnOutlineBackgroundColor = Color.clear
    public static let modalBtnOutlineBorderWidth: CGFloat = 1.5
    public static let modalBtnOutlineBorderColor = Theme.c(0xFFFFFF, 0.2)
    public static let modalBtnTextOutlineFontSize: CGFloat = 14
    public static let modalBtnTextOutlineFontWeight = "800"
    public static let modalBtnTextOutlineColor = Theme.c(0xFFFFFF)
    public static let modalReviewBtnMarginTop: CGFloat = 6
    public static let modalReviewBtnPaddingHorizontal: CGFloat = 28
    public static let modalReviewBtnPaddingVertical: CGFloat = 11
    public static let modalReviewBtnBorderRadius: CGFloat = 14
    public static let modalReviewBtnBackgroundColor = Theme.c(0xFFFFFF, 0.08)
    public static let modalReviewBtnBorderWidth: CGFloat = 1
    public static let modalReviewBtnBorderColor = Theme.c(0xFFFFFF, 0.2)
    public static let modalReviewBtnTextFontSize: CGFloat = 14
    public static let modalReviewBtnTextFontWeight = "700"
    public static let modalReviewBtnTextColor = Theme.c(0xD4E8F8)
    public static let reviewModalCardBackgroundColor = Theme.c(0x0D1B30)
    public static let reviewModalCardBorderRadius: CGFloat = 22
    public static let reviewModalCardPaddingVertical: CGFloat = 20
    public static let reviewModalCardPaddingHorizontal: CGFloat = 20
    public static let reviewModalCardWidth: CGFloat = 350
    public static let reviewModalCardBorderWidth: CGFloat = 1
    public static let reviewModalCardMaxHeight = "85%"
    public static let reviewModalTitleFontSize: CGFloat = 16
    public static let reviewModalTitleFontWeight = "900"
    public static let reviewModalTitleColor = Theme.c(0xFFFFFF)
    public static let reviewModalTitleTextAlign = "center"
    public static let reviewModalTitleLetterSpacing: CGFloat = 2
    public static let reviewModalTitleMarginBottom: CGFloat = 14
    public static let reviewLoadingWrapAlignItems = "center"
    public static let reviewLoadingWrapPaddingVertical: CGFloat = 40
    public static let reviewLoadingWrapGap: CGFloat = 12
    public static let reviewLoadingTextFontSize: CGFloat = 14
    public static let reviewLoadingTextFontWeight = "700"
    public static let reviewLoadingTextColor = Theme.c(0xFFFFFF)
    public static let reviewLoadingHintFontSize: CGFloat = 12
    public static let reviewLoadingHintColor = Theme.c(0xFFFFFF, 0.4)
    public static let reviewPlayersRowFlexDirection = "row"
    public static let reviewPlayersRowAlignItems = "center"
    public static let reviewPlayersRowMarginBottom: CGFloat = 12
    public static let reviewPlayerColFlex: CGFloat = 1
    public static let reviewPlayerColAlignItems = "center"
    public static let reviewPlayerColGap: CGFloat = 2
    public static let reviewPlayerLabelFontSize: CGFloat = 13
    public static let reviewPlayerLabelFontWeight = "700"
    public static let reviewPlayerLabelColor = Theme.c(0xFFFFFF, 0.7)
    public static let reviewPlayerLabelMarginBottom: CGFloat = 2
    public static let reviewAccuracyValueFontSize: CGFloat = 28
    public static let reviewAccuracyValueFontWeight = "900"
    public static let reviewAccuracyLabelFontSize: CGFloat = 10
    public static let reviewAccuracyLabelFontWeight = "600"
    public static let reviewAccuracyLabelColor = Theme.c(0xFFFFFF, 0.35)
    public static let reviewAccuracyLabelLetterSpacing: CGFloat = 1
    public static let reviewAccuracyLabelTextTransform = "uppercase"
    public static let reviewDividerWidth: CGFloat = 1
    public static let reviewDividerHeight: CGFloat = 50
    public static let reviewDividerBackgroundColor = Theme.c(0xFFFFFF, 0.12)
    public static let reviewDividerMarginHorizontal: CGFloat = 12
    public static let reviewGraphWrapAlignItems = "center"
    public static let reviewGraphWrapMarginBottom: CGFloat = 14
    public static let reviewClassificationsBlockGap: CGFloat = 5
    public static let reviewClassificationsBlockMarginBottom: CGFloat = 16
    public static let reviewClassRowFlexDirection = "row"
    public static let reviewClassRowAlignItems = "center"
    public static let reviewClassRowJustifyContent = "center"
    public static let reviewClassRowGap: CGFloat = 8
    public static let reviewClassCountFontSize: CGFloat = 15
    public static let reviewClassCountFontWeight = "800"
    public static let reviewClassCountWidth: CGFloat = 30
    public static let reviewClassCountTextAlign = "center"
    public static let reviewClassDotWidth: CGFloat = 8
    public static let reviewClassDotHeight: CGFloat = 8
    public static let reviewClassDotBorderRadius: CGFloat = 4
    public static let reviewClassLabelFontSize: CGFloat = 13
    public static let reviewClassLabelFontWeight = "600"
    public static let reviewClassLabelColor = Theme.c(0xFFFFFF, 0.7)
    public static let reviewClassLabelWidth: CGFloat = 90
    public static let reviewClassLabelTextAlign = "center"
    public static let reviewModalActionsFlexDirection = "row"
    public static let reviewModalActionsGap: CGFloat = 10
    public static let reviewStartBtnFlex: CGFloat = 1
    public static let reviewStartBtnPaddingVertical: CGFloat = 13
    public static let reviewStartBtnBorderRadius: CGFloat = 14
    public static let reviewStartBtnAlignItems = "center"
    public static let reviewStartBtnTextFontSize: CGFloat = 15
    public static let reviewStartBtnTextFontWeight = "900"
    public static let reviewStartBtnTextColor = Theme.c(0xFFFFFF)
    public static let reviewNewGameBtnFlex: CGFloat = 1
    public static let reviewNewGameBtnPaddingVertical: CGFloat = 13
    public static let reviewNewGameBtnBorderRadius: CGFloat = 14
    public static let reviewNewGameBtnBackgroundColor = Theme.c(0xFFFFFF, 0.08)
    public static let reviewNewGameBtnBorderWidth: CGFloat = 1
    public static let reviewNewGameBtnBorderColor = Theme.c(0xFFFFFF, 0.2)
    public static let reviewNewGameBtnAlignItems = "center"
    public static let reviewNewGameBtnTextFontSize: CGFloat = 15
    public static let reviewNewGameBtnTextFontWeight = "800"
    public static let reviewNewGameBtnTextColor = Theme.c(0xFFFFFF)
    public static let moveStripMaxHeight: CGFloat = 36
    public static let moveStripMarginHorizontal: CGFloat = 12
    public static let moveStripMarginBottom: CGFloat = 4
    public static let moveStripContentAlignItems = "center"
    public static let moveStripContentPaddingHorizontal: CGFloat = 4
    public static let moveStripContentGap: CGFloat = 2
    public static let movePairGroupFlexDirection = "row"
    public static let movePairGroupAlignItems = "center"
    public static let movePairGroupGap: CGFloat = 1
    public static let movePairNumFontSize: CGFloat = 11
    public static let movePairNumColor = Theme.c(0xFFFFFF, 0.3)
    public static let movePairNumPaddingHorizontal: CGFloat = 3
    public static let movePairNumFontFamily = "Menlo"
    public static let moveTokenPaddingHorizontal: CGFloat = 6
    public static let moveTokenPaddingVertical: CGFloat = 4
    public static let moveTokenBorderRadius: CGFloat = 6
    public static let moveTokenBackgroundColor = Color.clear
    public static let moveTokenActiveBackgroundColor = Theme.c(0xFDB022)
    public static let moveTokenTextFontSize: CGFloat = 12
    public static let moveTokenTextColor = Theme.c(0xFFFFFF, 0.65)
    public static let moveTokenTextFontFamily = "Menlo"
    public static let moveTokenTextActiveColor = Theme.c(0x07111F)
    public static let moveTokenTextActiveFontWeight = "700"
    public static let navBarFlexDirection = "row"
    public static let navBarAlignItems = "center"
    public static let navBarJustifyContent = "center"
    public static let navBarPaddingHorizontal: CGFloat = 12
    public static let navBarPaddingVertical: CGFloat = 6
    public static let navBarGap: CGFloat = 4
    public static let navBtnWidth: CGFloat = 44
    public static let navBtnHeight: CGFloat = 34
    public static let navBtnBorderRadius: CGFloat = 8
    public static let navBtnBackgroundColor = Theme.c(0xFFFFFF, 0.08)
    public static let navBtnJustifyContent = "center"
    public static let navBtnAlignItems = "center"
    public static let navBtnDisabledOpacity: CGFloat = 0.3
    public static let navBtnTextFontSize: CGFloat = 16
    public static let navBtnTextColor = Theme.c(0xFFFFFF)
    public static let navLiveBtnFlex: CGFloat = 1
    public static let navLiveBtnHeight: CGFloat = 34
    public static let navLiveBtnBorderRadius: CGFloat = 8
    public static let navLiveBtnBackgroundColor = Theme.c(0x1A3560)
    public static let navLiveBtnJustifyContent = "center"
    public static let navLiveBtnAlignItems = "center"
    public static let navLiveBtnMarginHorizontal: CGFloat = 4
    public static let navLiveBtnTextFontSize: CGFloat = 12
    public static let navLiveBtnTextFontWeight = "700"
    public static let navLiveBtnTextColor = Theme.c(0xFDB022)
    public static let navLiveIndicatorFlex: CGFloat = 1
    public static let navLiveIndicatorHeight: CGFloat = 34
    public static let navLiveIndicatorBorderRadius: CGFloat = 8
    public static let navLiveIndicatorBackgroundColor = Theme.c(0xFFFFFF, 0.04)
    public static let navLiveIndicatorJustifyContent = "center"
    public static let navLiveIndicatorAlignItems = "center"
    public static let navLiveIndicatorMarginHorizontal: CGFloat = 4
    public static let navLiveIndicatorFlexDirection = "row"
    public static let navLiveIndicatorGap: CGFloat = 5
    public static let navLiveDotWidth: CGFloat = 7
    public static let navLiveDotHeight: CGFloat = 7
    public static let navLiveDotBorderRadius: CGFloat = 4
    public static let navLiveDotBackgroundColor = Theme.c(0x4CAF50)
    public static let navLiveLabelFontSize: CGFloat = 10
    public static let navLiveLabelFontWeight = "700"
    public static let navLiveLabelColor = Theme.c(0x4CAF50)
    public static let navLiveLabelLetterSpacing: CGFloat = 1
    public static let openingPanelPosition = "absolute"
    public static let openingPanelLeft: CGFloat = 12
    public static let openingPanelRight: CGFloat = 12
    public static let openingPanelBottom: CGFloat = 60
    public static let openingPanelZIndex: CGFloat = 100
    public static let openingPanelMaxHeight: CGFloat = 280
    public static let openingPanelBackgroundColor = Theme.c(0x0A1937, 0.97)
    public static let openingPanelBorderRadius: CGFloat = 14
    public static let openingPanelBorderWidth: CGFloat = 1
    public static let openingPanelBorderColor = Theme.c(0xFDB022, 0.3)
    public static let openingPanelPadding: CGFloat = 12
    public static let openingPanelHeaderFlexDirection = "row"
    public static let openingPanelHeaderAlignItems = "center"
    public static let openingPanelHeaderJustifyContent = "space-between"
    public static let openingPanelHeaderMarginBottom: CGFloat = 8
    public static let openingPanelTitleFontSize: CGFloat = 13
    public static let openingPanelTitleFontWeight = "800"
    public static let openingPanelTitleColor = Theme.c(0xFDB022)
    public static let openingPanelActionsFlexDirection = "row"
    public static let openingPanelActionsGap: CGFloat = 8
    public static let openingPanelActionsAlignItems = "center"
    public static let openingRefreshBtnWidth: CGFloat = 28
    public static let openingRefreshBtnHeight: CGFloat = 28
    public static let openingRefreshBtnBorderRadius: CGFloat = 7
    public static let openingRefreshBtnBackgroundColor = Theme.c(0xFFFFFF, 0.08)
    public static let openingRefreshBtnJustifyContent = "center"
    public static let openingRefreshBtnAlignItems = "center"
    public static let openingRefreshTextFontSize: CGFloat = 16
    public static let openingRefreshTextColor = Theme.c(0xFDB022)
    public static let openingCloseBtnWidth: CGFloat = 28
    public static let openingCloseBtnHeight: CGFloat = 28
    public static let openingCloseBtnBorderRadius: CGFloat = 7
    public static let openingCloseBtnBackgroundColor = Theme.c(0xFFFFFF, 0.08)
    public static let openingCloseBtnJustifyContent = "center"
    public static let openingCloseBtnAlignItems = "center"
    public static let openingCloseTextFontSize: CGFloat = 14
    public static let openingCloseTextColor = Theme.c(0xFFFFFF, 0.6)
    public static let openingLoadingRowFlexDirection = "row"
    public static let openingLoadingRowAlignItems = "center"
    public static let openingLoadingRowGap: CGFloat = 8
    public static let openingLoadingRowPaddingVertical: CGFloat = 8
    public static let openingLoadingTextFontSize: CGFloat = 12
    public static let openingLoadingTextColor = Theme.c(0xFFFFFF, 0.5)
    public static let openingNameBadgeFlexDirection = "row"
    public static let openingNameBadgeAlignItems = "center"
    public static let openingNameBadgeGap: CGFloat = 6
    public static let openingNameBadgeMarginBottom: CGFloat = 8
    public static let openingNameBadgeBackgroundColor = Theme.c(0xFDB022, 0.12)
    public static let openingNameBadgeBorderRadius: CGFloat = 8
    public static let openingNameBadgePaddingHorizontal: CGFloat = 10
    public static let openingNameBadgePaddingVertical: CGFloat = 5
    public static let openingNameEcoFontSize: CGFloat = 11
    public static let openingNameEcoFontWeight = "800"
    public static let openingNameEcoColor = Theme.c(0xFDB022)
    public static let openingNameTextFontSize: CGFloat = 11
    public static let openingNameTextFontWeight = "600"
    public static let openingNameTextColor = Theme.c(0xD4E8F8)
    public static let openingNameTextFlex: CGFloat = 1
    public static let openingStatsBlockMarginBottom: CGFloat = 8
    public static let openingStatsLabelFontSize: CGFloat = 10
    public static let openingStatsLabelColor = Theme.c(0xFFFFFF, 0.4)
    public static let openingStatsLabelMarginBottom: CGFloat = 4
    public static let openingBarHeight: CGFloat = 8
    public static let openingBarBorderRadius: CGFloat = 4
    public static let openingBarFlexDirection = "row"
    public static let openingBarOverflow = "hidden"
    public static let openingBarMarginBottom: CGFloat = 4
    public static let openingBarSegHeight: CGFloat = 8
    public static let openingBarLegendFlexDirection = "row"
    public static let openingBarLegendJustifyContent = "space-between"
    public static let openingBarLegendTextFontSize: CGFloat = 10
    public static let openingBarLegendTextFontWeight = "600"
    public static let openingMovesBlockMarginTop: CGFloat = 2
    public static let openingMovesTitleFontSize: CGFloat = 11
    public static let openingMovesTitleFontWeight = "700"
    public static let openingMovesTitleColor = Theme.c(0xFFFFFF, 0.5)
    public static let openingMovesTitleMarginBottom: CGFloat = 6
    public static let openingMovesTitleLetterSpacing: CGFloat = 0.5
    public static let openingMoveRowFlexDirection = "row"
    public static let openingMoveRowAlignItems = "center"
    public static let openingMoveRowPaddingVertical: CGFloat = 4
    public static let openingMoveRowBorderBottomWidth: CGFloat = 1
    public static let openingMoveRowBorderBottomColor = Theme.c(0xFFFFFF, 0.05)
    public static let openingMoveRowGap: CGFloat = 8
    public static let openingMoveSanFontSize: CGFloat = 13
    public static let openingMoveSanFontWeight = "700"
    public static let openingMoveSanColor = Theme.c(0xFFFFFF)
    public static let openingMoveSanWidth: CGFloat = 44
    public static let openingMoveSanFontFamily = "Menlo"
    public static let openingMoveStatsFlex: CGFloat = 1
    public static let openingMoveStatsFontSize: CGFloat = 11
    public static let openingMoveStatsColor = Theme.c(0xFFFFFF, 0.5)
    public static let openingMoveRatingFontSize: CGFloat = 10
    public static let openingMoveRatingFontWeight = "600"
    public static let openingNoDataFontSize: CGFloat = 12
    public static let openingNoDataColor = Theme.c(0xFFFFFF, 0.4)
    public static let openingNoDataTextAlign = "center"
    public static let openingNoDataPaddingVertical: CGFloat = 8
    public static let bottomBarFlexDirection = "row"
    public static let bottomBarPaddingHorizontal: CGFloat = 12
    public static let bottomBarPaddingBottom: CGFloat = 8
    public static let bottomBarPaddingTop: CGFloat = 4
    public static let bottomBarGap: CGFloat = 8
    public static let actionBtnPaddingVertical: CGFloat = 10
    public static let actionBtnBorderRadius: CGFloat = 12
    public static let actionBtnAlignItems = "center"
    public static let actionBtnJustifyContent = "center"
    public static let actionBtnMinWidth: CGFloat = 44
    public static let actionBtnDisabledOpacity: CGFloat = 0.4
    public static let resignBtnFlex: CGFloat = 1
    public static let resignBtnBackgroundColor = Theme.c(0x7F1D1D)
    public static let resignBtnBorderWidth: CGFloat = 1
    public static let resignBtnBorderColor = Theme.c(0xFF5050, 0.3)
    public static let resignTextFontSize: CGFloat = 13
    public static let resignTextFontWeight = "700"
    public static let resignTextColor = Theme.c(0xFFCDD2)
    public static let takeBackBtnFlex: CGFloat = 1
    public static let takeBackBtnBackgroundColor = Theme.c(0x78350F)
    public static let takeBackBtnBorderWidth: CGFloat = 1
    public static let takeBackBtnBorderColor = Theme.c(0xFDB022, 0.3)
    public static let takeBackTextFontSize: CGFloat = 12
    public static let takeBackTextFontWeight = "700"
    public static let takeBackTextColor = Theme.c(0xFDE68A)
    public static let explorerBtnFlex: CGFloat = 1
    public static let explorerBtnBackgroundColor = Theme.c(0x0F2545)
    public static let explorerBtnBorderWidth: CGFloat = 1
    public static let explorerBtnBorderColor = Theme.c(0xFDB022, 0.3)
    public static let explorerBtnTextFontSize: CGFloat = 12
    public static let explorerBtnTextFontWeight = "700"
    public static let explorerBtnTextColor = Theme.c(0xFDB022)
    public static let newColorBtnFlex: CGFloat = 1
    public static let newColorBtnBackgroundColor = Theme.c(0x1B3050)
    public static let newColorBtnBorderWidth: CGFloat = 1
    public static let newColorBtnBorderColor = Theme.c(0xFFFFFF, 0.15)
    public static let newColorTextFontSize: CGFloat = 13
    public static let newColorTextFontWeight = "700"
    public static let newColorTextColor = Theme.c(0xFFFFFF)
    public static let promotionOverlayPosition = "absolute"
    public static let promotionOverlayTop: CGFloat = 0
    public static let promotionOverlayLeft: CGFloat = 0
    public static let promotionOverlayRight: CGFloat = 0
    public static let promotionOverlayBottom: CGFloat = 0
    public static let promotionOverlayBackgroundColor = Theme.c(0x000000, 0.8)
    public static let promotionOverlayJustifyContent = "center"
    public static let promotionOverlayAlignItems = "center"
    public static let promotionOverlayZIndex: CGFloat = 50
    public static let promotionDialogBackgroundColor = Theme.c(0x1A2942)
    public static let promotionDialogBorderRadius: CGFloat = 20
    public static let promotionDialogPadding: CGFloat = 24
    public static let promotionDialogWidth: CGFloat = 280
    public static let promotionTitleFontSize: CGFloat = 18
    public static let promotionTitleFontWeight = "bold"
    public static let promotionTitleColor = Theme.c(0xFFFFFF)
    public static let promotionTitleTextAlign = "center"
    public static let promotionTitleMarginBottom: CGFloat = 16
    public static let promotionOptionsGap: CGFloat = 10
    public static let promotionOptionBackgroundColor = Theme.c(0x4A90E2)
    public static let promotionOptionBorderRadius: CGFloat = 12
    public static let promotionOptionPadding: CGFloat = 14
    public static let promotionOptionAlignItems = "center"
    public static let promotionOptionFlexDirection = "row"
    public static let promotionOptionJustifyContent = "center"
    public static let promotionOptionGap: CGFloat = 12
    public static let promotionOptionTextFontSize: CGFloat = 16
    public static let promotionOptionTextFontWeight = "bold"
    public static let promotionOptionTextColor = Theme.c(0xFFFFFF)
    public static let graphBackgroundColor = Theme.c(0x1A2740)
    public static let graphBorderRadius: CGFloat = 6
    public static let graphHeight: CGFloat = 60
    public static let graphWhiteFill = Theme.c(0xFFFFFF, 0.25)
    public static let graphBlackFill = Theme.c(0x000000, 0.35)
    public static let graphMidStroke = Theme.c(0xFFFFFF, 0.15)
    public static let graphMidStrokeWidth: CGFloat = 1
    public static let graphCurveStroke = Theme.c(0xFDB022)
    public static let graphCurveStrokeWidth: CGFloat = 1.5
    public static let graphClampCp: CGFloat = 500
}

/// The board, from the same formula the Analysis Board and the puzzle solvers use — this screen
/// imports the same component. The FORMULA is what matters; these are the reference device.
public enum CoachBoard {
    public static let referenceWidth: CGFloat = 390
    public static let referenceHeight: CGFloat = 844
    public static let referencePixelRatio: CGFloat = 3
    public static let boardSize: CGFloat = 389.3333333333333
    public static let squareSize: CGFloat = 48.666666666666664

    /// `floor(screenWidthPx / 8) * 8 / pixelRatio` — recomputed per device rather than assumed.
    public static func size(width: CGFloat, pixelRatio: CGFloat) -> CGFloat {
        (floor((width * pixelRatio).rounded() / 8) * 8) / pixelRatio
    }
}

/// Level -> accent colour, from the source's own `COACH_DATA`. `play.tsx` applies it inline over
/// `modalBtn`, which is why that StyleSheet block carries no background of its own.
public enum CoachAccent {
    public static let level1 = Theme.c(0x4CAF50)
    public static let level2 = Theme.c(0xE91E8C)
    public static let level3 = Theme.c(0xFF6B35)
    public static let level4 = Theme.c(0xFF9BC4)
    public static let level5 = Theme.c(0xFDB022)

    public static func of(level: Int) -> Color {
        switch level {
        case 1: return level1
        case 2: return level2
        case 3: return level3
        case 4: return level4
        case 5: return level5
        default: return level1
        }
    }
}

/// One coach, verbatim from the source's own `COACH_DATA`.
///
/// `winMsg` / `loseMsg` are what the result card shows, so they are part of the roster rather
/// than of `CoachStrings`: they vary per coach, and a missing one is a blank modal.
public struct CoachProfile: Identifiable, Hashable {
    public let id: Int
    public let name: String
    public let role: String
    public let tagline: String
    public let intro: String
    public let thinkingMsg: String
    public let yourTurnMsg: String
    public let winMsg: String
    public let loseMsg: String
    public let rating: Int

    /// The button colour `play.tsx` applies inline over `modalBtn`.
    public var accent: Color { CoachAccent.of(level: id) }
}

public enum CoachRoster {
    public static let all: [CoachProfile] = [
        CoachProfile(id: 1, name: "Jaden Pogi", role: "Young Pawn Hero",
                     tagline: "Friendly \u{2022} Casual \u{2022} Just having fun",
                     intro: "Hey! I'm Jaden Pogi. I'm still learning too \u{2014} but I'll give it my best shot! Let's go! \u{1F604}",
                     thinkingMsg: "Umm... let me think for a sec... \u{1F914}",
                     yourTurnMsg: "Your move! I'll try to keep up! \u{1F605}",
                     winMsg: "Hehe, I got you! Don't worry \u{2014} you'll beat me next time! \u{1F604}",
                     loseMsg: "You won! Wow, you're so strong! \u{1F389} I still have a lot to learn!",
                     rating: 800),
        CoachProfile(id: 2, name: "Pretty Jade", role: "Little Princess Gambit",
                     tagline: "Tricky \u{2022} Unpredictable \u{2022} Surprising",
                     intro: "Hi! I'm Pretty Jade \u{2728} I love sneaky moves \u{2014} can you keep up with me? Hehe~",
                     thinkingMsg: "Planning something sneaky... \u{2728}",
                     yourTurnMsg: "Your move~ don't fall into my trap! \u{1F485}",
                     winMsg: "Hehe~ my trap worked perfectly! Better luck next time! \u{1F485}",
                     loseMsg: "Oh no! You beat me! You're really good! \u{2728}",
                     rating: 1500),
        CoachProfile(id: 3, name: "Handsome Jude", role: "Kuya Tactician",
                     tagline: "Sharp \u{2022} Aggressive \u{2022} Tactical",
                     intro: "I'm Handsome Jude. My tactics are sharp and aggressive \u{2014} ready for battle? \u{2694}\u{FE0F}",
                     thinkingMsg: "Calculating the sharpest line... \u{2694}\u{FE0F}",
                     yourTurnMsg: "Your move. Don't blunder \u{2014} I'll punish it. \u{1F624}",
                     winMsg: "Tactics win games! You'll need to sharpen your calculation! \u{2694}\u{FE0F}",
                     loseMsg: "You outplayed me! Respect \u{2014} that was genuinely sharp. \u{1F44A}",
                     rating: 1800),
        CoachProfile(id: 4, name: "Mommy Julie", role: "Mommy Strategist",
                     tagline: "Calm \u{2022} Positional \u{2022} Patient",
                     intro: "Hello! I'm Mommy Julie. Good chess is about patience and solid positions. Let's play! \u{1F338}",
                     thinkingMsg: "Finding the best positional move... \u{1F338}",
                     yourTurnMsg: "Take your time, anak. Good moves need patience. \u{1F338}",
                     winMsg: "Patience wins every time! Keep studying positions, anak! \u{1F338}",
                     loseMsg: "Well played! You showed such great patience today. I'm proud! \u{1F338}",
                     rating: 2000),
        CoachProfile(id: 5, name: "Coach Pogi", role: "The Master Trainer",
                     tagline: "Maximum strength \u{2022} Full power \u{2022} Unrelenting",
                     intro: "I'm Coach Pogi. I've mastered every position on this board. Show me what you've got. \u{1F451}",
                     thinkingMsg: "Analyzing at full depth... every line accounted for. \u{1F451}",
                     yourTurnMsg: "Your move. Every tempo matters at this level. \u{1F451}",
                     winMsg: "That's the gap in preparation. Study harder \u{2014} I'll be here. \u{1F451}",
                     loseMsg: "You defeated me. Truly exceptional play today. \u{1F451}",
                     rating: 2500),
    ]

    /// Out-of-range levels clamp rather than trap — spec 7 #35 is a deep link arriving with a
    /// non-numeric level and indexing `COACH_DATA[NaN]`.
    public static func of(level: Int) -> CoachProfile {
        all.first { $0.id == level } ?? all[0]
    }
}
