// GENERATED by tools/metrics/gen_coach_metrics.js — DO NOT HAND-EDIT.
//
// Spec 2.14, verbatim. The plain constants are emitted from `web-demo/js/coach-strings.js` so the
// two languages cannot hold different copy; the eight interpolating ones are shaped by a table in
// the generator, which fails if the JS grows or loses one.
//
// Eleven network-error strings and the `Premium` coach-lock badge are deliberately absent: there is
// no network and no lock. The Opening Explorer and the annotate/draw layer are not ported either —
// both are already unreachable in the shipping build.

import Foundation

public enum CoachStrings {
    public static let selectHeader = "\u{265E} PLAY AGAINST THE \u{265E}"
    public static let selectFamily = "BIYAHERONG COACH FAMILY BOTS"
    public static let selectBlurb = "Train your chess skills with fun AI opponents."
    public static let allowTakeBack = "Allow Take Back"
    public static let tagline = "Kabyahe mo sa pag improve!!"
    public static let subTagline = "Train \u{2022} Improve \u{2022} Have Fun"
    public static func elo(_ n: Int) -> String { "ELO \(n)" }
    public static let blurbBeginner = "Beginner friendly bot"
    public static let blurbTricky = "Tricky and unpredictable"
    public static let blurbSharp = "Sharp attacking style"
    public static let blurbCalm = "Calm positional player"
    public static let chooseSide = "\u{265F} Choose Your Side \u{265F}"
    public static let white = "White"
    public static let whiteSub = "You move first"
    public static let black = "Black"
    public static func blackSub(_ coach: String) -> String { "\(coach) goes first" }
    public static func unfinished(_ n: Int, _ colour: String) -> String { "Unfinished game \u{B7} \(n) moves as \(colour)" }
    public static let resumeTitle = "Continue Previous Game?"
    public static func resumeBody(_ n: Int, _ colour: String) -> String { "You have an unfinished game \u{2014} \(n) moves played as \(colour)." }
    public static let resumeAsk = "Would you like to continue or start fresh?"
    public static let newGame = "New Game"
    public static let continueGame = "Continue"
    public static let whiteChip = "\u{2B1C} White"
    public static let blackChip = "\u{2B1B} Black"
    public static let gameOverWon = "Game over \u{2014} You won!"
    public static let gameOver = "Game over"
    public static let gameOverDraw = "Game over \u{2014} Draw"
    public static let reviewing = "Reviewing game..."
    public static let results = "Results"
    public static func premove(_ from: String, _ to: String) -> String { "\u{26A1} \(from)\u{2192}\(to)" }
    public static let live = "LIVE"
    public static let liveButton = "\u{25B6} Live"
    public static let resign = "Resign"
    public static let resignTitle = "Resign?"
    public static func resignBody(_ coach: String) -> String { "\(coach) will win this game." }
    public static let keepPlaying = "Keep Playing"
    public static let takeBack = "\u{21A9} Take Back"
    public static let choosePromotion = "Choose Promotion"
    public static let queen = "Queen"
    public static let rook = "Rook"
    public static let bishop = "Bishop"
    public static let knight = "Knight"
    public static let youWon = "You Won!"
    public static let youLost = "You Lost"
    public static let draw = "Draw"
    public static let rematch = "Rematch"
    public static let reviewGame = "Review Game"
    public static let gameReview = "GAME REVIEW"
    public static func analyzing(_ done: Int, _ total: Int) -> String { "Analyzing\u{2026} \(done)/\(total)" }
    public static let you = "You"
    public static let accuracy = "Accuracy"
    public static let startReview = "Start Review"
    public static let drawThreefold = "Draw by threefold repetition!"
    public static let drawStalemate = "Stalemate \u{2014} It's a draw!"
    public static let drawFiftyMove = "Draw by the fifty-move rule."
    public static let drawInsufficient = "Draw \u{2014} not enough material to mate."
    public static let drawGeneric = "Draw! A well-balanced battle."
    public static func resigned(_ coach: String) -> String { "You resigned. \(coach) wins this round!" }
}
