// GENERATED by tools/metrics/gen_pairing_metrics.js — DO NOT HAND-EDIT.
//
// Spec 1.11, verbatim. The plain constants are emitted from `web-demo/js/pairing-metrics.js`'s
// `STR` table so the two languages cannot hold different copy; the interpolating ones are shaped by
// a table in the generator, which fails if the JS grows or loses one.
//
// Every network-error string from the React Native app is deliberately absent: there is no network.
// So are the free-plan limit messages — the one-time purchase removes the cap entirely.

import Foundation

public enum PairingStrings {
    public static let tournaments = "Tournaments"
    public static let listSub = "Swiss & Round Robin Manager"
    public static let emptyGlyph = "\u{265E}"
    public static let emptyTitle = "No Tournaments Yet"
    public static let emptySub = "Create your first chess tournament"
    public static let players = "Players"
    public static let rounds = "Rounds"
    public static let created = "Created"
    public static let createdDateFormat = "MMM d"
    public static let longPressHint = "Long press a card to delete"
    public static let fabPlus = "+"
    public static let newTournament = "New Tournament"
    public static let deleteTitle = "Delete Tournament"
    public static func deleteBody(_ name: String) -> String { "Delete \"\(name)\"? This cannot be undone." }
    public static let cancel = "Cancel"
    public static let deleteAction = "Delete"
    public static let swissBadge = "SWISS"
    public static let roundRobinBadge = "ROUND ROBIN"
    public static let statusSetup = "SETUP"
    public static let statusOngoing = "ONGOING"
    public static let statusFinished = "FINISHED"
    public static let chevron = "\u{203A}"
    public static let nameLabel = "Tournament Name"
    public static let namePlaceholder = "e.g. Manila Open 2026"
    public static let formatLabel = "Tournament Format"
    public static let swiss = "Swiss"
    public static let roundRobin = "Round Robin"
    public static let swissDesc = "Best for large events. Players face opponents with similar scores."
    public static let roundRobinDesc = "Everyone plays everyone. Best for smaller groups."
    public static let roundsLabel = "Number of Rounds"
    public static func recommended(_ n: Int, _ r: Int) -> String { "Recommended for \(n) players: \(r) rounds" }
    public static let roundsPlaceholder = "#"
    public static let rrNote = "Rounds are automatically determined by the number of players. Add players after creating the tournament."
    public static let createTournament = "Create Tournament"
    public static let required = "Required"
    public static let enterName = "Enter a tournament name"
    public static let swissGlyph = "S"
    public static let roundRobinGlyph = "R"
    public static func playersTab(_ n: Int) -> String { "Players (\(n))" }
    public static let roundsTab = "Rounds"
    public static let standingsTab = "Standings"
    public static func roundsMeta(_ cur: Int, _ total: Int) -> String { "R\(cur)/\(total)" }
    public static let noPlayers = "No players yet. Add players to get started."
    public static func ncfp(_ r: Int) -> String { "NCFP \(r)" }
    public static let bulkAdd = "Bulk Add"
    public static let addPlayerBtn = "+ Add Player"
    public static let removeTitle = "Remove Player"
    public static func removeBody(_ name: String) -> String { "Remove \(name)?" }
    public static let remove = "Remove"
    public static let removeGlyph = "\u{D7}"
    public static let lockedTitle = "Players Locked"
    public static let lockedBody = "Players can only be changed while the tournament is in setup."
    public static let share = "Share"
    public static func roundChip(_ n: Int) -> String { "R\(n)" }
    public static func byeLine(_ name: String) -> String { "\(name) \u{2014} BYE (1 pt)" }
    public static let vs = "vs"
    public static let resultWhite = "1-0"
    public static let resultBlack = "0-1"
    public static let resultDraw = "\u{BD}-\u{BD}"
    public static let needTwoPlayers = "Add at least 2 players first"
    public static let generateToStart = "Generate pairings to start the round"
    public static func generateRound(_ n: Int) -> String { "Generate Round \(n) Pairings" }
    public static let generateSchedule = "Generate Full Schedule"
    public static let tournamentComplete = "Tournament Complete"
    public static let colRank = "#"
    public static let colPlayer = "Player"
    public static let colPts = "Pts"
    public static let colW = "W"
    public static let colD = "D"
    public static let colL = "L"
    public static let colBch = "Bch"
    public static let colSB = "SB"
    public static let shareStandings = "Share Standings"
    public static let noPlayersToDisplay = "No players to display"
    public static let deletedTitle = "Tournament Not Found"
    public static let deletedBody = "This tournament has been deleted."
    public static let addPlayer = "Add Player"
    public static let nameRequired = "Name *"
    public static let fullName = "Full Name"
    public static let ncfpRating = "NCFP Rating"
    public static let playerNamePlaceholder = "Player name"
    public static let optional = "Optional"
    public static let add = "Add"
    public static let bulkAddTitle = "Bulk Add Players"
    public static let bulkAddSub = "One player per line. Add rating after name (optional)."
    public static let bulkPlaceholder = "Juan Dela Cruz\nMaria Santos 1500\nPedro Reyes 1200"
    public static func addNPlayers(_ n: Int) -> String { "Add \(n) Players" }
    public static let enterResult = "Enter Result"
    public static func board(_ n: Int) -> String { "Board \(n)" }
    public static let resultWhiteBig = "1 - 0"
    public static let resultWhiteSub = "White Wins"
    public static let resultDrawBig = "\u{BD} - \u{BD}"
    public static let resultDrawSub = "Draw"
    public static let resultBlackBig = "0 - 1"
    public static let resultBlackSub = "Black Wins"
    public static let clearResult = "Clear Result"
    public static let pairingNotes = "\u{26A0} Pairing Notes"
    public static func warnRepeat(_ a: String, _ b: String) -> String { "\(a) vs \(b) \u{2014} repeat pairing (no legal alternative)" }
    public static func warnColor(_ name: String) -> String { "\(name) \u{2014} colour preference not met" }
    public static func warnBye(_ name: String) -> String { "\(name) \u{2014} second bye awarded" }
    public static let brand = "BIYAHERONG CHESS COACH"
    public static func shareStandingsTitle(_ name: String) -> String { "\(name) \u{2014} Standings" }
    public static func shareSubtitle(_ n: Int, _ total: Int, _ type: String) -> String { "Round \(n) of \(total) \u{2022} \(type)" }
    public static let hashtags = "#BiyaherongChess  #ChessPH"
    public static let siteUrl = "biyaherongchesscoach.com"
    public static let textBrand = "\u{265F}\u{FE0F} Biyaherong Chess Coach"
    public static let textRule = "\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}"
    public static let textTrophy = "\u{1F3C6} "
    public static let textClipboard = "\u{1F4CB} "
    public static func textBoard(_ n: Int) -> String { "Bd \(n): " }
    public static let textBye = " \u{2014} BYE"
}
