// GENERATED by tools/metrics/gen_video_metrics.js — DO NOT HAND-EDIT.
//
// Every number, colour and category glyph the Tutorial Videos screens draw, from
// tools/metrics/video_styles.json, which extract_video_styles.js re-derives from the
// React Native source. Nothing here is transcribed.
//
// The COPY is not here — see VideoStrings, which is hand-written and pinned by
// tools/qa/replay_videos.js. The RN keeps its strings in JSX rather than in a table, and
// this app says things the RN never had to: it can be offline, and the RN could not.
//

import SwiftUI

/// Extracted from `app/(app)/user/tutorial-videos/index.tsx` by tools/metrics/extract_video_styles.js.
public enum VideoList {
    public static let containerFlex: CGFloat = 1
    public static let containerBackgroundColor = Theme.c(0x0F1A2E)
    public static let headerFlexDirection = "row"
    public static let headerAlignItems = "center"
    public static let headerJustifyContent = "space-between"
    public static let headerPaddingHorizontal: CGFloat = 16
    public static let headerPaddingVertical: CGFloat = 12
    public static let headerBorderBottomWidth: CGFloat = 1
    public static let headerBorderBottomColor = Theme.c(0x1A2942)
    public static let backButtonWidth: CGFloat = 40
    public static let backButtonHeight: CGFloat = 40
    public static let backButtonJustifyContent = "center"
    public static let backButtonAlignItems = "center"
    public static let backIconFontSize: CGFloat = 26
    public static let backIconColor = Theme.c(0xFFFFFF)
    public static let headerTitleFontSize: CGFloat = 18
    public static let headerTitleFontWeight = "bold"
    public static let headerTitleColor = Theme.c(0xFFFFFF)
    public static let loadingContainerFlex: CGFloat = 1
    public static let loadingContainerJustifyContent = "center"
    public static let loadingContainerAlignItems = "center"
    public static let loadingTextMarginTop: CGFloat = 12
    public static let loadingTextFontSize: CGFloat = 14
    public static let loadingTextColor = Theme.c(0x8BA3C7)
    public static let emptyContainerFlex: CGFloat = 1
    public static let emptyContainerJustifyContent = "center"
    public static let emptyContainerAlignItems = "center"
    public static let emptyContainerPaddingHorizontal: CGFloat = 40
    public static let emptyIconFontSize: CGFloat = 48
    public static let emptyIconMarginBottom: CGFloat = 16
    public static let emptyTitleFontSize: CGFloat = 22
    public static let emptyTitleFontWeight = "bold"
    public static let emptyTitleColor = Theme.c(0xFFFFFF)
    public static let emptyTitleMarginBottom: CGFloat = 8
    public static let emptySubtitleFontSize: CGFloat = 14
    public static let emptySubtitleColor = Theme.c(0x8BA3C7)
    public static let emptySubtitleTextAlign = "center"
    public static let paywallContainerFlex: CGFloat = 1
    public static let paywallContainerJustifyContent = "center"
    public static let paywallContainerAlignItems = "center"
    public static let paywallContainerPaddingHorizontal: CGFloat = 40
    public static let paywallIconFontSize: CGFloat = 56
    public static let paywallIconMarginBottom: CGFloat = 20
    public static let paywallLabelFontSize: CGFloat = 22
    public static let paywallLabelFontWeight = "bold"
    public static let paywallLabelColor = Theme.c(0xFDB022)
    public static let paywallLabelMarginBottom: CGFloat = 16
    public static let paywallMessageFontSize: CGFloat = 16
    public static let paywallMessageColor = Theme.c(0xFFFFFF)
    public static let paywallMessageTextAlign = "center"
    public static let paywallMessageMarginBottom: CGFloat = 10
    public static let paywallMessageLineHeight: CGFloat = 24
    public static let paywallSubtextFontSize: CGFloat = 13
    public static let paywallSubtextColor = Theme.c(0x8BA3C7)
    public static let paywallSubtextTextAlign = "center"
    public static let paywallSubtextMarginBottom: CGFloat = 32
    public static let paywallSubtextLineHeight: CGFloat = 20
    public static let subscribeButtonBackgroundColor = Theme.c(0xFDB022)
    public static let subscribeButtonBorderRadius: CGFloat = 12
    public static let subscribeButtonPaddingVertical: CGFloat = 14
    public static let subscribeButtonPaddingHorizontal: CGFloat = 40
    public static let subscribeButtonTextColor = Theme.c(0x0F1A2E)
    public static let subscribeButtonTextFontSize: CGFloat = 16
    public static let subscribeButtonTextFontWeight = "bold"
    public static let listContentPaddingHorizontal: CGFloat = 16
    public static let listContentPaddingTop: CGFloat = 12
    public static let listContentPaddingBottom: CGFloat = 28
    public static let sectionHeaderFlexDirection = "row"
    public static let sectionHeaderAlignItems = "center"
    public static let sectionHeaderMarginTop: CGFloat = 20
    public static let sectionHeaderMarginBottom: CGFloat = 10
    public static let sectionHeaderGap: CGFloat = 8
    public static let sectionAccentWidth: CGFloat = 3
    public static let sectionAccentHeight: CGFloat = 18
    public static let sectionAccentBorderRadius: CGFloat = 2
    public static let sectionTitleFontSize: CGFloat = 15
    public static let sectionTitleFontWeight = "700"
    public static let sectionTitleFlex: CGFloat = 1
    public static let sectionCountFontSize: CGFloat = 11
    public static let sectionCountColor = Theme.c(0x5A7A9A)
    public static let sectionCountFontWeight = "500"
    public static let videoCardFlexDirection = "row"
    public static let videoCardBackgroundColor = Theme.c(0x162136)
    public static let videoCardBorderRadius: CGFloat = 14
    public static let videoCardOverflow = "hidden"
    public static let videoCardMarginBottom: CGFloat = 10
    public static let videoCardBorderWidth: CGFloat = 1
    public static let videoCardBorderColor = Theme.c(0xFFFFFF, 0.05)
    public static let videoCardElevation: CGFloat = 3
    public static let videoCardShadowColor = Theme.c(0x000000)
    public static let videoCardShadowOffsetWidth: CGFloat = 0
    public static let videoCardShadowOffsetHeight: CGFloat = 2
    public static let videoCardShadowOpacity: CGFloat = 0.2
    public static let videoCardShadowRadius: CGFloat = 4
    public static let thumbWrapBackgroundColor = Theme.c(0x0D1520)
    public static let thumbWrapPosition = "relative"
    public static let thumbWrapFlexShrink: CGFloat = 0
    public static let thumbWidth = "100%"
    public static let thumbHeight = "100%"
    public static let playOverlayPosition = "absolute"
    public static let playOverlayLeft: CGFloat = 0
    public static let playOverlayRight: CGFloat = 0
    public static let playOverlayTop: CGFloat = 0
    public static let playOverlayBottom: CGFloat = 0
    public static let playOverlayJustifyContent = "center"
    public static let playOverlayAlignItems = "center"
    public static let playOverlayBackgroundColor = Theme.c(0x000000, 0.28)
    public static let playBtnWidth: CGFloat = 36
    public static let playBtnHeight: CGFloat = 36
    public static let playBtnBorderRadius: CGFloat = 18
    public static let playBtnBackgroundColor = Theme.c(0xFDB022, 0.92)
    public static let playBtnJustifyContent = "center"
    public static let playBtnAlignItems = "center"
    public static let playBtnIconFontSize: CGFloat = 14
    public static let playBtnIconColor = Theme.c(0xFFFFFF)
    public static let playBtnIconMarginLeft: CGFloat = 2
    public static let cardInfoFlex: CGFloat = 1
    public static let cardInfoPadding: CGFloat = 12
    public static let cardInfoJustifyContent = "center"
    public static let cardInfoGap: CGFloat = 6
    public static let catChipAlignSelf = "flex-start"
    public static let catChipBorderRadius: CGFloat = 6
    public static let catChipPaddingVertical: CGFloat = 3
    public static let catChipPaddingHorizontal: CGFloat = 8
    public static let catChipTextFontSize: CGFloat = 10
    public static let catChipTextFontWeight = "700"
    public static let catChipTextLetterSpacing: CGFloat = 0.3
    public static let cardTitleFontSize: CGFloat = 14
    public static let cardTitleFontWeight = "700"
    public static let cardTitleColor = Theme.c(0xFFFFFF)
    public static let cardTitleLineHeight: CGFloat = 19
    public static let cardDescFontSize: CGFloat = 12
    public static let cardDescColor = Theme.c(0x7A9AB8)
    public static let cardDescLineHeight: CGFloat = 17
    public static let cardDateFontSize: CGFloat = 10
    public static let cardDateColor = Theme.c(0x4A6A8A)
    public static let cardDateMarginTop: CGFloat = 2
}

/// Extracted from `app/(app)/user/tutorial-videos/play.tsx` by tools/metrics/extract_video_styles.js.
public enum VideoPlay {
    public static let rootFlex: CGFloat = 1
    public static let rootBackgroundColor = Theme.c(0x000000)
    public static let topBarFlexDirection = "row"
    public static let topBarAlignItems = "center"
    public static let topBarPaddingHorizontal: CGFloat = 12
    public static let topBarPaddingBottom: CGFloat = 12
    public static let topBarGap: CGFloat = 8
    public static let topBarBackgroundColor = Theme.c(0x000000, 0.55)
    public static let backBtnWidth: CGFloat = 40
    public static let backBtnHeight: CGFloat = 40
    public static let backBtnBorderRadius: CGFloat = 20
    public static let backBtnBackgroundColor = Theme.c(0xFFFFFF, 0.15)
    public static let backBtnJustifyContent = "center"
    public static let backBtnAlignItems = "center"
    public static let backIconFontSize: CGFloat = 22
    public static let backIconColor = Theme.c(0xFFFFFF)
    public static let backIconFontWeight = "bold"
    public static let titleTextFlex: CGFloat = 1
    public static let titleTextFontSize: CGFloat = 15
    public static let titleTextFontWeight = "600"
    public static let titleTextColor = Theme.c(0xFFFFFF)
    public static let fullscreenBtnWidth: CGFloat = 40
    public static let fullscreenBtnHeight: CGFloat = 40
    public static let fullscreenBtnBorderRadius: CGFloat = 20
    public static let fullscreenBtnBackgroundColor = Theme.c(0xFFFFFF, 0.15)
    public static let fullscreenBtnJustifyContent = "center"
    public static let fullscreenBtnAlignItems = "center"
    public static let middleAreaFlex: CGFloat = 1
    public static let controlBarBackgroundColor = Theme.c(0x0F1A2E, 0.92)
    public static let controlBarPaddingHorizontal: CGFloat = 16
    public static let controlBarPaddingTop: CGFloat = 12
    public static let controlBarGap: CGFloat = 6
    public static let controlBarBorderTopWidth: CGFloat = 1
    public static let controlBarBorderTopColor = Theme.c(0xFFFFFF, 0.08)
    public static let seekRowFlexDirection = "row"
    public static let seekRowAlignItems = "center"
    public static let seekRowGap: CGFloat = 8
    public static let timeTextFontSize: CGFloat = 12
    public static let timeTextColor = Theme.c(0x8BA3C7)
    public static let timeTextMinWidth: CGFloat = 38
    public static let timeRightTextAlign = "right"
    public static let seekTrackContainerFlex: CGFloat = 1
    public static let seekTrackContainerJustifyContent = "center"
    public static let trackBgPosition = "absolute"
    public static let trackBgLeft: CGFloat = 0
    public static let trackBgRight: CGFloat = 0
    public static let trackBgBackgroundColor = Theme.c(0xFFFFFF, 0.25)
    public static let trackFillPosition = "absolute"
    public static let trackFillLeft: CGFloat = 0
    public static let trackFillBackgroundColor = Theme.c(0xFDB022)
    public static let trackThumbPosition = "absolute"
    public static let trackThumbBackgroundColor = Theme.c(0xFDB022)
    public static let trackThumbShadowColor = Theme.c(0xFDB022)
    public static let trackThumbShadowOpacity: CGFloat = 0.7
    public static let trackThumbShadowRadius: CGFloat = 4
    public static let trackThumbElevation: CGFloat = 4
    public static let buttonsRowFlexDirection = "row"
    public static let buttonsRowJustifyContent = "center"
    public static let buttonsRowAlignItems = "center"
    public static let buttonsRowGap: CGFloat = 24
    public static let buttonsRowPaddingVertical: CGFloat = 4
    public static let seekBtnAlignItems = "center"
    public static let seekBtnPadding: CGFloat = 8
    public static let seekBtnMinWidth: CGFloat = 56
    public static let seekIconFontSize: CGFloat = 26
    public static let seekIconColor = Theme.c(0xFFFFFF)
    public static let seekLabelFontSize: CGFloat = 11
    public static let seekLabelColor = Theme.c(0x8BA3C7)
    public static let seekLabelMarginTop: CGFloat = 2
    public static let playPauseBtnWidth: CGFloat = 56
    public static let playPauseBtnHeight: CGFloat = 56
    public static let playPauseBtnBorderRadius: CGFloat = 28
    public static let playPauseBtnBackgroundColor = Theme.c(0xFDB022)
    public static let playPauseBtnJustifyContent = "center"
    public static let playPauseBtnAlignItems = "center"
    public static let playPauseIconFontSize: CGFloat = 24
    public static let playPauseIconColor = Theme.c(0x0F1A2E)
}

/// What each section looks like.
///
/// The ORDER lives in VideoLibrary.categoryOrder (the Core) because grouping is domain logic;
/// this table is only its skin, and `replay_videos.js` pins the two together.
public enum VideoCategoryStyle {

    public struct Meta: Equatable, Sendable {
        public let accent: Color
        public let chipBackground: Color
        public let glyph: String
    }

    public static let all: [String: Meta] = [
        "Opening": Meta(accent: Theme.c(0x7BB3F0), chipBackground: Theme.c(0x1D3461), glyph: "📖"),
        "Middlegame": Meta(accent: Theme.c(0xA78BFA), chipBackground: Theme.c(0x2D1B69), glyph: "⚔️"),
        "Endgame": Meta(accent: Theme.c(0xFDB022), chipBackground: Theme.c(0x3B2200), glyph: "👑"),
        "General": Meta(accent: Theme.c(0x5CC264), chipBackground: Theme.c(0x1A3320), glyph: "♟️"),
        "Uncategorized": Meta(accent: Theme.c(0x8BA3C7), chipBackground: Theme.c(0x1A2942), glyph: "📂"),
    ]

    /// An unknown category never reaches here — `VideoLibrary.categoryKey` folds it to
    /// Uncategorized first — but the fallback keeps a missing entry from rendering as nothing.
    public static func meta(_ name: String) -> Meta {
        all[name] ?? all[VideoLibrary.uncategorized]!
    }
}

/// The card thumbnail. `THUMB_H` is FOLDED from the source's own
/// `Math.round(THUMB_W * (16 / 9))` rather than typed — a 9:16 portrait still.
public enum VideoThumb {
    public static let width: CGFloat = 90
    public static let height: CGFloat = 160
}
