#!/usr/bin/env node
/*
 * replay_videos.js — the Tutorial Videos Swift says what the JavaScript that has run says.
 *
 *     node tools/qa/replay_videos.js
 *
 * `swift` is not on PATH here, so `VideoLibrary.swift`, `ContentClient.swift`, `VideoStrings.swift`
 * and `VideoScreens.swift` were written blind. Same mitigation as every phase: pull the concrete
 * values out of the Swift SOURCE TEXT and compare them with the JS twin, which `js_goldens.js`
 * proves by running it.
 *
 * `VideoMetrics.swift` is NOT checked here — it is generated by `gen_video_metrics.js` from
 * `video_styles.json`, so there is no transcription step for a check to sit in. What IS checked is
 * the two things the generator cannot know: that the copy matches, and that the screens make the
 * same DECISIONS.
 *
 * ## The decision this file exists for
 *
 * The screen has four ways to refuse and the ORDER matters. A user who is offline AND has no
 * subscription must be shown the paywall, not "check your wifi": the entitlement is decided
 * on-device by StoreKit and is knowable with the radio off, so it is the answer we are certain of,
 * and sending somebody to find a connection for a screen they could not open with one is a wasted
 * trip. Two screens in two languages agreeing about that is exactly the kind of thing that drifts.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const JS = path.join(ROOT, 'web-demo', 'js');
const UI = path.join(ROOT, 'DemoApp', 'Sources', 'BiyaherongUI');
const CORE = path.join(ROOT, 'Sources', 'BiyaherongCoachCore');

let passed = 0;
const failures = [];
const expect = (c, what) => { c ? passed++ : failures.push(what); };
const eq = (got, want, what) => expect(got === want,
  `${what}: Swift says ${JSON.stringify(want)}, JS gives ${JSON.stringify(got)}`);

function code(src) {
  return src.replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/^[ \t]*\/\/\/.*$/gm, '')
    .replace(/^[ \t]*\/\/.*$/gm, '');
}

function read(dir, file) {
  const full = path.join(dir, file);
  if (!fs.existsSync(full)) { failures.push('missing ' + file); return ''; }
  return fs.readFileSync(full, 'utf8');
}

/** A `static let x = "…"` inside `enum Ns`, with `\u{XXXX}` escapes resolved. */
function swString(src, name) {
  const m = new RegExp(`static let ${name}\\s*=\\s*"((?:[^"\\\\]|\\\\.)*)"`).exec(src);
  if (!m) return null;
  return m[1]
    .replace(/\\u\{([0-9A-Fa-f]+)\}/g, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/\\n/g, '\n')
    .replace(/\\"/g, '"')
    .replace(/\\\\/g, '\\');
}

const LIB_SWIFT = read(CORE, 'VideoLibrary.swift');
const STR_SWIFT = read(UI, 'VideoStrings.swift');
const CC_SWIFT = read(UI, 'ContentClient.swift');
const SCREENS_SWIFT = read(UI, 'VideoScreens.swift');

const LIB = require(path.join(JS, 'video-library.js'));
const STR = require(path.join(JS, 'video-strings.js'));
const CC = require(path.join(JS, 'content-client.js'));

// ── 1. The twins run ────────────────────────────────────────────────────────────

for (const [name, mod, floor] of [['video-library.js', LIB, 25], ['content-client.js', CC, 5]]) {
  const t = mod.selfTest();
  passed += t.passed;
  if (!t.ok) failures.push(...t.failures.map((f) => name + ': ' + f));
  expect(t.passed >= floor, `${name} ran ${t.passed} assertions — it must not shrink`);
}

// ── 2. The categories are ONE list, in three places ─────────────────────────────
//
// The Core owns the order because grouping is domain logic; the metrics own the skin; the RN owns
// both. All three have to agree or a section renders with no colour, or in the wrong place, or not
// at all.
{
  const m = /categoryOrder = \[([^\]]+)\]/.exec(code(LIB_SWIFT));
  expect(!!m, 'VideoLibrary.categoryOrder is in the Swift');
  if (m) {
    const swift = m[1].split(',').map((s) => s.trim().replace(/^"|"$/g, ''));
    eq(LIB.CATEGORY_ORDER.join(','), swift.join(','), 'the category order');
  }
  eq(LIB.UNCATEGORIZED, swString(LIB_SWIFT, 'uncategorized'), 'the name of the catch-all');

  const extraction = path.join(ROOT, 'tools', 'metrics', 'video_styles.json');
  if (fs.existsSync(extraction)) {
    const rn = JSON.parse(fs.readFileSync(extraction, 'utf8'))
      .screens.list.moduleConstants.CATEGORY_ORDER;
    expect(Array.isArray(rn), 'the extraction carries CATEGORY_ORDER');
    if (Array.isArray(rn)) {
      eq(LIB.CATEGORY_ORDER.join(','), rn.join(','),
        'and it is the RN source\'s own order, not a copy that drifted');
    }
  }

  const metrics = require(path.join(JS, 'video-metrics.js'));
  for (const cat of LIB.CATEGORY_ORDER) {
    const meta = metrics.CATEGORIES[cat];
    expect(!!meta, `${cat} has a style — a section with no colour and no glyph renders as nothing`);
    if (meta) expect(!!meta.glyph && !!meta.accent, `${cat}'s style is filled in`);
  }
}

// ── 3. The deviation: an unknown category is VISIBLE ────────────────────────────
//
// The RN builds sections as `CATEGORY_ORDER.filter(...)`, so a video whose category is not in that
// list is grouped and then silently dropped — the admin sees it saved and visible, and the app shows
// a catalogue missing it. Both ports fold the unknown into Uncategorized instead.
{
  eq(LIB.categoryKey('Tactics'), LIB.UNCATEGORIZED,
    'an unknown category folds into Uncategorized in the JS');
  expect(/categoryOrder\.contains\(trimmed\) \? trimmed : uncategorized/.test(code(LIB_SWIFT)),
    'and in the Swift');
  eq(LIB.categoryKey(null), LIB.UNCATEGORIZED, 'so does a missing one');
  eq(LIB.categoryKey('  '), LIB.UNCATEGORIZED, 'and a blank one');

  const grouped = LIB.sections(LIB.parse(JSON.stringify({ videos: [
    { id: 1, title: 'T', category: 'Tactics', video_url: 't.mp4' },
  ] })));
  eq(grouped.length, 1, 'a lone unknown-category video still produces a section');
  eq(grouped[0].title, LIB.UNCATEGORIZED, 'and it is Uncategorized rather than nothing');
}

// ── 4. Nothing unplayable is ever listed ────────────────────────────────────────

{
  expect(/guard let videoURL = stringValue\(row\["video_url"\]\), !videoURL\.isEmpty else \{ continue \}/
    .test(code(LIB_SWIFT)),
    'the Swift skips a row with no video_url — a card that cannot play looks like the feature is '
    + 'broken rather than like the catalogue is short');
  eq(LIB.parse('[{"id":1,"title":"x"}]').length, 0, 'and so does the JS');
  expect(/guard !title\.isEmpty else \{ continue \}/.test(code(LIB_SWIFT)),
    'a blank title is skipped in the Swift');
  eq(LIB.parse('[{"id":1,"title":"  ","video_url":"a.mp4"}]').length, 0, 'and in the JS');
}

// ── 5. The copy ─────────────────────────────────────────────────────────────────

{
  const plain = ['title', 'loading', 'emptyGlyph', 'emptyTitle', 'emptySub', 'playGlyph',
                 'lockGlyph', 'paywallLabel', 'paywallMessage', 'paywallSubtext', 'subscribe',
                 'onlineGlyph', 'onlineTitle', 'offlineBody', 'offlineSub', 'onlineNote', 'retry',
                 'errorTitle', 'errorBody', 'notConfiguredTitle', 'notConfiguredBody'];
  for (const key of plain) {
    eq(STR.STR[key], swString(STR_SWIFT, key), `VideoStrings.${key}`);
  }
  expect(plain.length >= 20, `${plain.length} strings compared — the list must not shrink`);

  eq(STR.count(1), '1 video', 'one video is singular');
  eq(STR.count(12), '12 videos', 'and twelve are not');
  expect(/n == 1 \? "video" : "videos"/.test(code(STR_SWIFT)), 'the Swift pluralises the same way');

  // The two the client asked for, stated as properties rather than as literals so the reason
  // survives a rewording.
  expect(/internet/i.test(STR.STR.onlineNote),
    'the standing note says the screen needs a connection');
  expect(/internet/i.test(STR.STR.offlineBody),
    'and so does the offline state — this is an ONLINE feature, and the client asked to be told so');
  expect(!/internet|wifi/i.test(STR.STR.notConfiguredBody),
    'but the unpublished state does NOT blame the connection: the app has nowhere to look, and '
    + 'sending the user to fix their wifi would send them to fix the one thing that is working');
}

// ── 6. The refusal ORDER, in both languages ─────────────────────────────────────
//
// Premium first. An offline free user sees the paywall, because the entitlement is knowable with
// the radio off and the connection is not the thing standing in their way.
{
  const swift = code(SCREENS_SWIFT);
  const iPremium = swift.indexOf('!premium.isPremium');
  const iConfig = swift.indexOf('!ContentClient.isConfigured');
  const iOffline = swift.indexOf('failure.isOffline');
  expect(iPremium >= 0 && iConfig > iPremium && iOffline > iConfig,
    'the Swift tests premium, then configured, then offline — in that order');

  const js = code(fs.readFileSync(path.join(JS, 'videos.js'), 'utf8'));
  const jPremium = js.indexOf('!state.isPremium');
  const jConfig = js.indexOf('!CC.isConfigured()');
  const jOffline = js.indexOf('CC.FAILURE.offline');
  expect(jPremium >= 0 && jConfig > jPremium && jOffline > jConfig,
    'and the JS tests them in the SAME order — an offline free user must meet the paywall, not a '
    + 'connection error for a screen they could not open with a connection');
}

// ── 7. The transport ────────────────────────────────────────────────────────────

{
  eq(CC.MANIFEST_URL, swString(CC_SWIFT, 'manifestURL'),
    'both languages point at the same manifest');
  expect(/^https:\/\//.test(CC.MANIFEST_URL),
    'over TLS — a catalogue is a list of URLs the app will fetch and play, and in plaintext anyone '
    + 'on the network chooses what those are');
  expect(/\/api\/content\/tutorial-videos$/.test(CC.MANIFEST_URL),
    'and at the content route. /api/tutorial-videos is inside auth:sanctum and this app holds no '
    + 'token by design, so that path 401s forever and reads on a phone as a broken feature');
  expect(CC.isConfigured(), 'so the JS reports it configured');

  // ── The receipt gate ──────────────────────────────────────────────────────────────────────────
  //
  // The catalogue used to be public: one `curl` returned every video URL. The caller now proves a
  // live subscription with a StoreKit signed transaction, which the backend checks against Apple's
  // pinned root. These assertions exist because none of it compiles here, and because a transport
  // that quietly stopped sending the receipt would still work perfectly — until the server was
  // fixed, at which point every user would lose the screen at once.
  expect(/httpMethod = "POST"/.test(code(CC_SWIFT)),
    'the Swift POSTs. The receipt is kilobytes of certificate chain, which is a body\'s job — '
    + 'nginx default header buffers are not generous enough to make a header a safe habit');
  expect(/method: 'POST'/.test(code(fs.readFileSync(path.join(JS, 'content-client.js'), 'utf8'))), 'and so does the JS');
  expect(/"jws": receipt/.test(code(CC_SWIFT)) || /\["jws": receipt\]/.test(code(CC_SWIFT)),
    'the Swift sends the receipt under the key the controller reads');
  expect(/jws: receipt/.test(code(fs.readFileSync(path.join(JS, 'content-client.js'), 'utf8'))), 'and the JS sends the same key');
  expect(/func videos\(receipt: String\)/.test(code(CC_SWIFT)),
    'and the receipt is a REQUIRED parameter, not an optional the caller can forget');

  expect(/statusCode == 401/.test(code(CC_SWIFT)),
    'a 401 is read specially by the Swift');
  expect(/status === 401/.test(code(fs.readFileSync(path.join(JS, 'content-client.js'), 'utf8'))), 'and by the JS');
  expect(/case notSubscribed/.test(code(CC_SWIFT)),
    'both languages have a notSubscribed outcome — the server refusing a receipt is NOT a broken '
    + 'catalogue and must not be reported as one');
  expect(typeof CC.FAILURE.notSubscribed === 'string', 'the JS names it too');
  expect(CC.FAILURE.notSubscribed !== CC.FAILURE.offline,
    'and it is distinct from offline: sending somebody to check their wifi when their subscription '
    + 'lapsed is the wrong instruction twice over');

  // Refusing without a receipt costs no round trip in either language.
  eq(CC.videos('') instanceof Promise, true, 'the JS returns a promise even when it refuses early');

  // Neither language may cache an authorised response. The server says no-store for the same
  // reason: a proxy holding this body would serve it to somebody who showed no receipt.
  expect(/reloadIgnoringLocalCacheData/.test(code(CC_SWIFT)),
    'the Swift does not reuse a cached catalogue');
  expect(!/max-age/.test(code(CC_SWIFT)), 'and asks for no shared caching');
  expect(/cache: 'no-store'/.test(code(fs.readFileSync(path.join(JS, 'content-client.js'), 'utf8'))), 'the JS says no-store');

  // The screens agree about what a refused receipt means.
  expect(/failure == \.notSubscribed[\s\S]{0,240}VideoPaywall/.test(code(SCREENS_SWIFT)),
    'the Swift screen sends a refused receipt to the PAYWALL, not to an error the user cannot act '
    + 'on — the server holds the content, so when it and StoreKit disagree the server wins');
  expect(/FAILURE\.notSubscribed[\s\S]{0,400}paywall\(/.test(code(fs.readFileSync(path.join(JS, 'videos.js'), 'utf8'))),
    'and the JS screen does the same');
  expect(/case notConfigured/.test(code(CC_SWIFT)),
    'and the Swift KEEPS a failure case for an empty URL that is NOT a network error. Unreachable '
    + 'in shipping config, and it stays: blanking the URL must not send the user to fix their wifi');

  // The distinction that keeps "no videos yet" from reading as "something broke".
  expect(CC.looksLikeCatalogue('{"videos":[]}'), 'an empty catalogue IS a catalogue in the JS');
  expect(!CC.looksLikeCatalogue('<!doctype html>'), 'an HTML error page is not');
  expect(/object\["videos"\] is \[Any\]/.test(code(CC_SWIFT)),
    'and the Swift draws the same distinction');
  expect(/!videos\.isEmpty \|\| looksLikeCatalogue\(data\)/.test(code(CC_SWIFT)),
    'an empty-but-valid manifest is a success in the Swift, not a failure');
}

// ── 8. The parity core stays a parity core ──────────────────────────────────────

{
  expect(!/URLSession|URLRequest|import SwiftUI|import UIKit/.test(LIB_SWIFT),
    'VideoLibrary opens no socket and imports no UI — it parses bytes somebody else fetched');
  expect(/^import Foundation$/m.test(LIB_SWIFT), 'Foundation only');
}

const result = {
  passed,
  failures,
  ok: failures.length === 0,
  summary: failures.length === 0
    ? `ReplayVideos: ${passed} Swift expectations confirmed against the JS`
    : `ReplayVideos: ${passed} confirmed, ${failures.length} BROKEN\n`
      + failures.map((f) => '  x ' + f).join('\n'),
};

if (require.main === module) {
  console.log(result.summary);
  process.exit(result.ok ? 0 : 1);
}

module.exports = { run: () => result, selfTest: () => result };
