import Foundation

/// SAN and UCI **parsing** — the inverse of `ChessPosition.san(for:)` and `Move.uci`
/// (Analysis Board; Chess primitives, brief §11).
///
/// Pinned by the `san_parse` golden group: 3,105 cases generated by the real
/// `App\Services\ChessEngine` from the sibling Laravel repo, each asserting the parsed UCI, the
/// resulting six-field FEN, and the position key. The same algorithm is mirrored in
/// `web-demo/js/engine.js`, where it was written and proven first — see PORTING_NOTES.
///
/// Parsing is **two-tier**, and both tiers earn their place:
///
///   1. *Exact.* Generate SAN for every legal move with `san(for:)` — the very generator whose
///      output we are inverting — and compare. This makes the inverse correct by construction, so
///      the parser and the generator can never drift apart. It resolves all 3,105 golden cases.
///   2. *Tolerant.* Real PGN exporters emit spellings we would never produce: over-disambiguated
///      (`Nbd2`, `N1d2`), long algebraic (`Nb1d2`, `Nb1-d2`), `x` omitted (`ed5`), `=` omitted or
///      parenthesised (`a8Q`, `a8(Q)`). Tier 1 was measured against those forms and misses every
///      one, so tier 2 re-reads the token structurally and filters the legal moves.
///
/// Failure is always `nil`, never a throw — Core contains no `throws` anywhere, and this matches
/// `init?(fen:)`, `Square.index(_:)` and `ChessAI.bestMove(_:persona:using:)`.
extension ChessPosition {

    // MARK: SAN

    /// Strip everything that carries no positional meaning: the `e.p.` marker, check/mate marks,
    /// `!?` annotations, and the zero-spelling of castling.
    ///
    /// The order (en-passant marker first, then suffixes) mirrors `normalizeSan` in
    /// `web-demo/js/engine.js` exactly, so the twin cannot diverge on a pathological input.
    public static func normalizedSAN(_ text: String) -> String {
        var t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if t.lowercased().hasSuffix("e.p.") {
            t = String(t.dropLast(4)).trimmingCharacters(in: .whitespaces)
        }
        while let last = t.last, "+#!?".contains(last) { t = String(t.dropLast()) }
        if t == "0-0" { return "O-O" }
        if t == "0-0-0" { return "O-O-O" }
        return t
    }

    /// Parse a SAN move in this position. Returns `nil` for anything illegal, ambiguous or
    /// unreadable.
    public func move(forSAN text: String) -> Move? {
        let want = ChessPosition.normalizedSAN(text)
        if want.isEmpty { return nil }
        let moves = legalMoves()
        // Tier 1 — exact, against our own generator.
        for m in moves where ChessPosition.normalizedSAN(self.san(for: m)) == want { return m }
        // Tier 2 — tolerant.
        return looseMove(want, in: moves)
    }

    // MARK: UCI

    /// Parse a UCI move (`"e2e4"`, `"e7e8q"`) in this position. Matched against the legal moves, so
    /// a well-formed but illegal move yields `nil` just as malformed input does.
    public func move(forUCI uci: String) -> Move? {
        let cs = Array(uci.trimmingCharacters(in: .whitespacesAndNewlines))
        guard cs.count == 4 || cs.count == 5 else { return nil }
        guard let from = Square.index(String(cs[0 ..< 2])),
              let to = Square.index(String(cs[2 ..< 4])) else { return nil }
        var promo: PieceKind?
        if cs.count == 5 {
            guard let p = ChessPosition.promotionKind(cs[4]) else { return nil }
            promo = p
        }
        for m in legalMoves() where m.from == from && m.to == to && m.promotion == promo { return m }
        return nil
    }

    // MARK: Tolerant scanner
    //
    // Deliberately hand-rolled rather than a regex. The JavaScript twin uses one pattern; here a
    // character scan avoids every question a regex would raise in a Foundation-only, cross-platform
    // target. Semantics are identical — see PORTING_NOTES.
    //
    // Grammar, matching the twin's pattern:
    //     [NBRQK]? [a-h]? [1-8]? [x:-]? [a-h][1-8] ( '='? '('? [NBRQnbrq] ')'? )?
    //
    // It is read from the right, because the destination square is the one unambiguous anchor: any
    // SAN ends in a rank digit unless it ends in a promotion letter (castling never reaches here —
    // tier 1 always resolves `O-O` / `O-O-O`).

    /// The four legal promotion targets, either case. `nil` for anything else — notably `k`/`K`,
    /// which some sloppy writers emit and which can never be a promotion.
    private static func promotionKind(_ ch: Character) -> PieceKind? {
        switch ch {
        case "N", "n": return .knight
        case "B", "b": return .bishop
        case "R", "r": return .rook
        case "Q", "q": return .queen
        default: return nil
        }
    }

    private func looseMove(_ want: String, in moves: [Move]) -> Move? {
        var cs = Array(want)
        guard cs.count >= 2 else { return nil }

        // 1. Trailing promotion. A SAN ending in a letter can only be a promotion, since every
        //    destination square ends in a digit. The length guard keeps a two-character token like
        //    "ab" from being read as a promotion to bishop.
        var promo: PieceKind?
        if cs.last == ")" { cs.removeLast() }
        if cs.count >= 3, let last = cs.last, let p = ChessPosition.promotionKind(last) {
            promo = p
            cs.removeLast()
            if cs.last == "(" { cs.removeLast() }
            if cs.last == "=" { cs.removeLast() }
        }

        // 2. Destination square.
        guard cs.count >= 2, let dest = Square.index(String(cs.suffix(2))) else { return nil }
        cs.removeLast(2)

        // 3. Head: optional piece letter, optional from-file, optional from-rank, optional
        //    capture/separator mark. Anything left over means this is not SAN.
        var kind: PieceKind = .pawn
        var i = 0
        if i < cs.count {
            switch cs[i] {
            case "N": kind = .knight; i += 1
            case "B": kind = .bishop; i += 1
            case "R": kind = .rook;   i += 1
            case "Q": kind = .queen;  i += 1
            case "K": kind = .king;   i += 1
            default: break
            }
        }
        var fromFile: Int?
        var fromRank: Int?
        if i < cs.count, let a = cs[i].asciiValue, a >= 97, a <= 104 { fromFile = Int(a) - 97; i += 1 }
        if i < cs.count, let a = cs[i].asciiValue, a >= 49, a <= 56 { fromRank = Int(a) - 49; i += 1 }
        if i < cs.count, cs[i] == "x" || cs[i] == ":" || cs[i] == "-" { i += 1 }
        guard i == cs.count else { return nil }

        // 4. Filter the legal moves. A unique survivor is the answer; anything else is ambiguous.
        var hits: [Move] = []
        for m in moves {
            guard let pc = squares[m.from] else { continue }
            if m.to != dest || pc.kind != kind { continue }
            if let f = fromFile, Square.file(m.from) != f { continue }
            if let r = fromRank, Square.rank(m.from) != r { continue }
            if let p = promo {
                if m.promotion != p { continue }
            } else if let actual = m.promotion, actual != .queen {
                // An unspecified promotion means queen, the universal convention.
                continue
            }
            hits.append(m)
        }
        return hits.count == 1 ? hits[0] : nil
    }
}
