// GENERATED by tools/metrics/gen_coach_book.js — DO NOT HAND-EDIT.
//
// The opening book's tables (spec §2.3), emitted from `web-demo/js/coach-book.js` so the two
// languages hold ONE book rather than two readings of one. The lookup that walks these rows is in
// `CoachBook.swift` and is transliterated, not generated.
//
// 63 repertoire rows across levels 2, 3, 4, 5, plus level 1's two junk pools.

import Foundation

extension CoachBook {

    /// Seven moves per side. `sanHistory.count < bookPlies` is the spec's own gate.
    public static let bookPlies = 14

    /// Level 1 — Jaden. Not a line, a POOL: uniform over openings that are all bad on purpose.
    /// This IS the level's character, and after move 1 the depth-2 search takes over.
    public static let l1White: [String] = ["f2f3", "g2g4", "b2b4", "a2a3", "h2h3", "b1a3"]
    public static let l1Black: [String] = ["f7f6", "a7a6", "h7h6", "g7g5", "b8a6"]

    /// Levels 2–5. Order does not matter: the lookup is an exact match on the history, so at most
    /// one row can apply.
    public static let rules: [Int: [CoachGame.Side: [Row]]] = [
    2: [
        .white: [
            Row(history: [], move: "e2e4"),
            Row(history: ["e4", "e5"], move: "f2f4"),
            Row(history: ["e4", "e5", "f4", "exf4"], move: "g1f3"),
            Row(history: ["e4", "c5"], move: "d2d4"),
            Row(history: ["e4", "e6"], move: "d2d4"),
            Row(history: ["e4", "d6"], move: "d2d4"),
        ],
        .black: [
            Row(history: ["e4"], move: "e7e5"),
            Row(history: ["e4", "e5", "Nf3"], move: "f7f5"),
            Row(history: ["d4"], move: "g8f6"),
            Row(history: ["d4", "Nf6", "c4"], move: "e7e5"),
        ],
    ],
    3: [
        .white: [
            Row(history: [], move: "e2e4"),
            Row(history: ["e4", "e5"], move: "g1f3"),
            Row(history: ["e4", "e5", "Nf3", "Nc6"], move: "f1c4"),
            Row(history: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"], move: "c2c3"),
            Row(history: ["e4", "e5", "Nf3", "Nf6"], move: "f3e5"),
        ],
        .black: [
            Row(history: ["e4"], move: "c7c5"),
            Row(history: ["e4", "c5", "Nf3"], move: "d7d6"),
            Row(history: ["e4", "c5", "Nf3", "d6", "d4"], move: "c5d4"),
            Row(history: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4"], move: "g8f6"),
            Row(history: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3"], move: "a7a6"),
            Row(history: ["e4", "c5", "c3"], move: "d7d5"),
            Row(history: ["e4", "c5", "d4"], move: "c5d4"),
            Row(history: ["d4"], move: "g8f6"),
            Row(history: ["d4", "Nf6", "c4"], move: "c7c5"),
            Row(history: ["d4", "Nf6", "c4", "c5", "d5"], move: "e7e6"),
            Row(history: ["d4", "Nf6", "c4", "c5", "d5", "e6", "Nc3"], move: "e6d5"),
            Row(history: ["d4", "Nf6", "Nf3"], move: "g7g6"),
        ],
    ],
    4: [
        .white: [
            Row(history: [], move: "d2d4"),
            Row(atPly: 2, move: "g1f3"),
            Row(atPly: 4, move: "c1f4"),
            Row(atPly: 6, move: "e2e3"),
            Row(atPly: 8, move: "c2c3"),
            Row(atPly: 10, move: "f1d3"),
        ],
        .black: [
            Row(history: ["e4"], move: "e7e6"),
            Row(history: ["e4", "e6", "d4"], move: "d7d5"),
            Row(history: ["e4", "e6", "d4", "d5", "e5"], move: "c7c5"),
            Row(history: ["e4", "e6", "d4", "d5", "Nc3"], move: "g8f6"),
            Row(history: ["e4", "e6", "d4", "d5", "Nd2"], move: "g8f6"),
            Row(history: ["d4"], move: "g8f6"),
            Row(history: ["d4", "Nf6", "c4"], move: "e7e6"),
            Row(history: ["d4", "Nf6", "c4", "e6", "Nc3"], move: "f8b4"),
            Row(history: ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "Nf3"], move: "b7b6"),
            Row(history: ["d4", "Nf6", "Nf3"], move: "e7e6"),
        ],
    ],
    5: [
        .white: [
            Row(history: [], move: "e2e4"),
            Row(history: ["e4", "c5"], move: "d2d4"),
            Row(history: ["e4", "c5", "d4", "cxd4"], move: "c2c3"),
            Row(history: ["e4", "c5", "d4", "cxd4", "c3", "dxc3"], move: "b1c3"),
            Row(history: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6"], move: "g1f3"),
            Row(history: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6", "Nf3", "d6"], move: "f1c4"),
            Row(history: ["e4", "e5"], move: "g1f3"),
            Row(history: ["e4", "e5", "Nf3", "Nc6"], move: "f1b5"),
            Row(history: ["e4", "e5", "Nf3", "Nf6"], move: "f3e5"),
        ],
        .black: [
            Row(history: ["e4"], move: "d7d5"),
            Row(history: ["e4", "d5", "exd5"], move: "d8d5"),
            Row(history: ["e4", "d5", "exd5", "Qxd5", "Nc3"], move: "d5a5"),
            Row(history: ["e4", "d5", "exd5", "Qxd5", "Nc3", "Qa5", "d4"], move: "g8f6"),
            Row(history: ["e4", "d5", "e5"], move: "c7c5"),
            Row(history: ["d4"], move: "d7d5"),
            Row(history: ["d4", "d5", "c4"], move: "c7c6"),
            Row(history: ["d4", "d5", "c4", "c6", "Nf3"], move: "g8f6"),
            Row(history: ["d4", "d5", "c4", "c6", "Nc3"], move: "g8f6"),
            Row(history: ["d4", "d5", "Nf3"], move: "g8f6"),
            Row(history: ["d4", "d5", "Bf4"], move: "c7c6"),
        ],
    ],
    ]
}
