import Foundation

/// The bundled offline ECO opening book (Analysis Board).
///
/// Replaces the original app's Lichess masters explorer, which cannot exist offline. The book is
/// generated by `tools/eco/build_eco.php` from lichess-org/chess-openings (CC0) and keyed by
/// `ChessPosition.positionKey` — the four-field FEN with a dead en-passant square cleared — so
/// **transpositions resolve**: reaching a position by a different move order finds the same entry.
///
/// Two kinds of row, both "in book":
/// - **named** — an ECO line *ends* here; carries an ECO code and a name.
/// - **pass-through** — a line merely traverses here; the name is empty.
///
/// Only named rows change the displayed opening; a miss keeps the **last known** name, so a position
/// twenty moves into the Najdorf still reads "Najdorf" rather than going blank (spec Part 12.2).
/// Both kinds count as in-book, which is what makes the `book` classification tier meaningful — the
/// server could never produce that tier because it had no opening database at all.
///
/// Deliberately **pure, with no file IO**: giving the Parity Core a resource would create a
/// `Bundle.module` in a manifest that cannot be compile-verified on the development machine. The
/// caller supplies the TSV text; the UI layer owns loading it from the app bundle.
///
/// Mirrored by `web-demo/js/opening-book.js`.
public struct OpeningBook: Sendable {

    public struct Entry: Equatable, Sendable {
        public let eco: String
        /// Empty for a pass-through position — in book, but carrying no name of its own.
        public let name: String

        public init(eco: String, name: String) { self.eco = eco; self.name = name }

        /// A pass-through row: in book, but it does not change the displayed opening.
        public var isNamed: Bool { !name.isEmpty }
    }

    private let rows: [String: Entry]

    /// Parse the generated book. Lines are `key\teco\tname`; `#` comments and blanks are skipped.
    ///
    /// A pass-through row ends in a trailing tab with an empty name, so the split must **keep** the
    /// empty final field rather than dropping it.
    public init(tsv: String) {
        var rows: [String: Entry] = [:]
        for rawLine in tsv.split(separator: "\n", omittingEmptySubsequences: true) {
            if rawLine.hasPrefix("#") { continue }
            let parts = rawLine.split(separator: "\t", omittingEmptySubsequences: false)
            guard parts.count >= 2 else { continue }
            let key = String(parts[0])
            if key.isEmpty { continue }
            let name = parts.count >= 3 ? String(parts[2]) : ""
            rows[key] = Entry(eco: String(parts[1]), name: name)
        }
        self.rows = rows
    }

    /// Build directly from parsed rows — used by tests and by any future binary format.
    public init(rows: [String: Entry]) { self.rows = rows }

    public var count: Int { rows.count }

    /// The row for a position key, or `nil` when the position is out of book.
    public func entry(for key: String) -> Entry? { rows[key] }

    /// Is this position in the book at all? Pass-through rows count. This is what drives `book`.
    public func contains(_ key: String) -> Bool { rows[key] != nil }

    /// The entry only when it actually carries a name; a pass-through row yields `nil`.
    public func named(_ key: String) -> Entry? {
        guard let e = rows[key], e.isNamed else { return nil }
        return e
    }

    /// The opening to display at this position. A named hit wins; a pass-through row or a miss keeps
    /// whatever was showing before.
    public func nameFor(_ key: String, lastKnown: Entry?) -> Entry? {
        named(key) ?? lastKnown
    }

    /// One legal move that stays in the book.
    public struct Continuation: Equatable, Sendable {
        public let san: String
        public let uci: String
        public let key: String
        public let entry: Entry
    }

    /// Every legal move from `position` that lands on a book position — what the Opening Explorer
    /// panel lists. Sorted by SAN so the order is deterministic in both languages.
    public func continuations(from position: ChessPosition) -> [Continuation] {
        var out: [Continuation] = []
        for m in position.legalMoves() {
            let after = position.makeMove(m)
            let key = after.positionKey
            guard let e = rows[key] else { continue }
            out.append(Continuation(san: position.san(for: m), uci: m.uci, key: key, entry: e))
        }
        return out.sorted { $0.san < $1.san }
    }

    /// Which plies of a game are still in book. `positionKeys[0]` is the start position, so the
    /// result holds indices >= 1 — the same indices `GameReview.MoveEvaluation.moveIndex` uses.
    public func bookPlies(_ positionKeys: [String]) -> [Int] {
        var out: [Int] = []
        var i = 1
        while i < positionKeys.count {
            if contains(positionKeys[i]) { out.append(i) }
            i += 1
        }
        return out
    }

    /// How many plies from the start the game stayed in book, stopping at the first miss.
    public func bookPrefixLength(_ positionKeys: [String]) -> Int {
        var n = 0
        var i = 1
        while i < positionKeys.count, contains(positionKeys[i]) { n += 1; i += 1 }
        return n
    }
}
